### ISSUE TITLE
zsh: exec format error: ./.local/share/bob/v0.8.3/nvim-linux64/bin/nvim

### ISSUE THREAD

**Issue by NexusNovaz** [MordechaiHadad/bob#100]
Running ARM Ubuntu on Oracle cloud. Bob installed x86_64. Installed bob using cargo install --git https://github.com/MordechaiHadad/bob.git (if it matters)

╭─ubuntu on instance-20221207-0257 in ~ 23-03-07 - 17:50:13
╰─ file ./.local/share/bob/v0.8.3/nvim-linux64/bin/nvim
./.local/share/bob/v0.8.3/nvim-linux64/bin/nvim: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=5d575f4797452c24c5893fdb1c0317e2d8be2340, for GNU/Linux 3.2.0, with debug_info, not stripped

**Comment by MordechaiHadad** [comment]
yeah unfortunately bob only installs versions from neovim github releases which don't include arm versions sadly...
I can probably open a neovim issue regarding this, but I don't have control of this.

**Comment by NexusNovaz** [comment]
Ahh, thats a shame. Just found [this](https://github.com/neovim/neovim/issues/15143) issue on neovims repo.

**Comment by MordechaiHadad** [comment]
You can probably just use bob to build neovim if you still want to have bob installed, otherwise it is kinda useless on arm sadly

**Comment by NexusNovaz** [comment]
> 

Sorry, how can you do this with bob?

**Comment by MordechaiHadad** [comment]
you simply do `bob install <commit-hash>`

**Comment by necrophcodr** [comment]
> you simply do `bob install <commit-hash>` I haven't tried it on arm but i think it should work

So this would work with `bob install <commit-hash-of-tagged-release>`, correct?

**Comment by MordechaiHadad** [comment]
> > you simply do `bob install <commit-hash>` I haven't tried it on arm but i think it should work
> 
> So this would work with `bob install <commit-hash-of-tagged-release>`, correct?

Absolutely

**Comment by 0atman** [comment]
> you simply do `bob install <commit-hash>` I haven't tried it on arm but i think it should work

I can confirm that this works great with the current release hash on the nvim page :tada: I don't mind manually updating that hash now and then until the upstream project figures out their aarch64 binaries.

Thanks @MordechaiHadad !

**Comment by 0atman** [comment]
To be clear, I ran:

```
$ bob install 129264dbb41404b94b835baadfc3fa25ffac3d3e
$ bob use 129264d
```

**Comment by 0atman** [comment]
YEP! 
Also, I guess I just needed the use line, right?

**Comment by MordechaiHadad** [comment]
> YEP! Also, I guess I just needed the use line, right?

yeah, use auto invokes install, unless u disable it with `--no-install`

**Comment by damingerdai** [comment]
i also meet the issue in wsl

**Comment by damingerdai** [comment]
> i also meet the issue in wsl

Fixed this issue by downloading manually

**Comment by MordechaiHadad** [comment]
This issue is fixed on MacOS arm for now
