### ISSUE TITLE
Error: Couldn't find bob.json

### ISSUE THREAD

**Issue by Aasim-A** [MordechaiHadad/bob#107]
First off, thanks for making this tool!

After the recent update that addresses `nightly` not being updated, I'm getting this error when running `bob use nightly`.
The output of the command is:
```
Mar 13 01:19:18.878  INFO Looking for nightly updates
Mar 13 01:19:18.957 ERROR Error: Couldn't find bob.json
```
`bob list` output:
```
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
│  nightly  │  Installed  │
└───────────┴─────────────┘
```
I have tried `bob erase` and reinstalled `nightly`, it installs fine but errors when trying to use it. I'm on version `2.1.2`

**Comment by MordechaiHadad** [comment]
Can you ls inside of `~/.local/share/bob/nightly` and if bob.json exists cat it?

Also damn you are living in the future March 13th

**Comment by Aasim-A** [comment]
It only contains `nvim-linux64` folder

**Comment by MordechaiHadad** [comment]
@Aasim-A can you try the PR @utkarshgupta137 created?
