### ISSUE TITLE
Error: Couldn't create downloads directory

### ISSUE THREAD

**Issue by princejoogie** [MordechaiHadad/bob#112]
Related to #101 which should've been "fixed" but still getting the error on the latest version (v2.1.3)

Output:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/47204120/226100814-0421a333-1974-4440-8ddc-7ec003bbfed8.png">

System info:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/47204120/226100847-1489d2ba-bbac-47c7-8e6d-5fb2658fc56d.png">

**Comment by MordechaiHadad** [comment]
@princejoogie damn... can you try this binary? https://github.com/MordechaiHadad/bob/actions/runs/4375873244
run the usual bob commands and see what path it outputs?

**Comment by princejoogie** [comment]
@MordechaiHadad the artifact has expired in the actions tab. I tried downloading v2.1.1 which includes the fix for the macos downloads dir, same output

<img width="734" alt="image" src="https://user-images.githubusercontent.com/47204120/226148702-82e1efb3-eae3-4686-9cbc-b5058f679fea.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/47204120/226148724-042a653a-e743-496a-ba82-d3d29e273f8e.png">

**Comment by alokthakrar** [comment]
Hello, I believe I'm also running into this issue when attempting to set up Bob. 
I have essentially the same system: 
<img width="264" alt="Screenshot 2024-07-22 at 10 56 40 AM" src="https://github.com/user-attachments/assets/e4cd82f4-4f52-471d-b659-4b7860286736">

And here's the issue: 
<img width="498" alt="Screenshot 2024-07-22 at 10 57 38 AM" src="https://github.com/user-attachments/assets/e99a2508-ba2c-4e62-a34d-19b8bb2ee603">

Not sure if it's relevant but I installed the standard version of bob from source.

**Comment by mblarsen** [comment]
I'm experiencing this on 

```
$ bob --version
bob-nvim 4.0.2

$ uname --all
Linux plumb 6.8.0-1021-aws #23-Ubuntu SMP Mon Dec  9 23:59:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Error:

```
$ bob install stable
Feb 02 16:35:00.835  INFO Fetching latest version
Feb 02 16:35:01.605 ERROR Error: Couldn't create downloads directory
```
