### ISSUE TITLE
Is there a way to include nvim-qt on Windows?

### ISSUE THREAD

**Issue by Kamholtz** [MordechaiHadad/bob#113]
Hi, 

This is the first time I have used bob, is there a way to include nvim-qt? I did not see it mentioned in the readme. In the case that it actually should be available, there are the steps I took to get started:

```
bob install nightly
bob use nightly
ls C:\Users\xxx\AppData\Local\bob\nvim-bin\


    Directory: C:\Users\xxx\AppData\Local\bob\nvim-bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        18/03/2023   9:10 PM        4768768 nvim.exe
```

**Comment by MordechaiHadad** [comment]
Currently you can just copy nvim-qt to the nvim-bin folder, if you really need it I will simply add it and create a new release

**Comment by Kamholtz** [comment]
Having nvim-qt copied automatically would be much appreciated as I use it frequently. Copying only `nvim-qt.exe` to the bin folder was not sufficient in my test. I had to copy all the dependencies out of `nvim-win64` to the bin folder to use nvim-qt.

**Comment by MordechaiHadad** [comment]
Fair enough, I will try proxying nvim-qt just like nvim bin.

Also sidetracking a bit why do you bother using nvim-qt for a neovim gui? there are much better alternatives like gonvim.

**Comment by Kamholtz** [comment]
Every few months I try goneovim, fvim and neovide. Each time I have encountered issues I can't easily ignore. Stuff like blank tabs, obscured completion popups from the cursor moving sporadically, occasional crashes and other strange rendering issues. Nvim-qt has never been my first pick for a GUI, but it has been reliable, so I haven't had much patience with the other options to try find workarounds unfortunately.

**Comment by MordechaiHadad** [comment]
@Kamholtz can you copy the bob exe from the PR's actions artifacts? once downloaded rename bob to nvim-qt, add it to nvim-bin and run `nvim-qt.exe` from the cmd line

**Comment by Kamholtz** [comment]
I can confirm it's working for me @MordechaiHadad. Thank you very much!

**Comment by MordechaiHadad** [comment]
> I can confirm it's working for me @MordechaiHadad. Thank you very much!

Awesome you can keep it like this and you wont have to touch nvim-bin again, Ill add a feature for bob to auto add nvim-qt to nvim-bin.

Also I assume you use a config, did you feel any increase in startup time(became slower)?

**Comment by Kamholtz** [comment]
> Also I assume you use a config, did you feel any increase in startup time(became slower)?

I use a reasonably large personal config, I did not notice an increase in startup time.

>@Kamholtz can you remove nvim-qt, switch to a different version and see if nvim-qt is automatically copied to nvim-bin/

I have downloaded the artifacts from [comit 83e6906](https://github.com/MordechaiHadad/bob/pull/116/commits/83e690674645fe26c472c3ff89e0ce56992c9068) and have confirmed that after removing nvim-qt, I can `use` a different version and observe nvim-qt being copied to `nvim-bin`. I have been able to successfully switch between nightly and stable.

I see that there have been further changes since that commit. Let me know if you're ready for me to do another test.

**Comment by MordechaiHadad** [comment]
that's awesome to hear, if you can try current build, if it works fine I will create a new release!

**Comment by Kamholtz** [comment]
Using the artifacts from [7d4c0b7b0dbf13f7cd9bf971c8b3e9c27517d82d ](https://github.com/MordechaiHadad/bob/pull/116/commits/7d4c0b7b0dbf13f7cd9bf971c8b3e9c27517d82d) I have confirmed that the executables appear in `nvim-bin` after the command `bob use nightly`. I have also confirmed that I can switch from nightly and stable successfully.

Thank you for taking the time to support this!
