### ISSUE TITLE
nvim-qt.exe proxy opens a console window

### ISSUE THREAD

**Issue by sid-6581** [MordechaiHadad/bob#118]
The nvim-qt proxy added in #116 opens a console window on Windows when executed, so every instance of nvim-qt I have open now has two windows open until I exit nvim-qt. Any way to get around that?

**Comment by MordechaiHadad** [comment]
I can try finding a way, but I am not sure as of now

**Comment by MordechaiHadad** [comment]
@sid-6581 I managed to find a way
