### ISSUE TITLE
ERROR Error: environment variable not found

### ISSUE THREAD

**Issue by qujihan** [MordechaiHadad/bob#121]
Hello, I am using docker in macbook M1 and the image I am using is ubuntu: 22.04. I get this error either by downloading directly or installing with cargo. How should this be solved?

<img width="629" alt="image" src="https://user-images.githubusercontent.com/43026824/230432676-1a5b686a-211a-419d-a4d6-dccbdfe7eb98.png">

**Comment by MordechaiHadad** [comment]
@qujihan what does `echo $USER` give you?

**Comment by qujihan** [comment]
> @qujihan what does `echo $USER` give you?

is empty, one line blank

**Comment by MordechaiHadad** [comment]
@qujihan I assume you created the docker container using the dockerfile in the repo, therefore try creating a new one from the new branch and test to see if this fixes it

**Comment by qujihan** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/43026824/230780530-0de5ed08-c817-44f4-8719-9e5c729d2b7c.png">
<img width="979" alt="image" src="https://user-images.githubusercontent.com/43026824/230780554-ef5609cf-9d47-4643-b08b-04300dfc82f0.png">
There is no fix as of the moment I sent this message

**Comment by MordechaiHadad** [comment]
@qujihan Use `cargo install --git https://github.com/MordechaiHadad/bob.git --branch fix/home-fallback`

**Comment by qujihan** [comment]
Great, problem solved. Thank you! (But it seems that neovim doesn't offer the aarch64 version, so it's still a bit problematic to use.)

**Comment by MordechaiHadad** [comment]
> Great, problem solved. Thank you! (But it seems that neovim doesn't offer the aarch64 version, so it's still a bit problematic to use.)

Yeah it doesn't yet sadly
