### ISSUE TITLE
`bob use stable` breaks with the 0.9.0 release

### ISSUE THREAD

**Issue by bartdorsey** [MordechaiHadad/bob#122]
```thread 'main' panicked at 'Failed to spawn child process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/echo/.cargo/registry/src/github.com-1ecc6299db9ec823/bob-nvim-2.2.0/src/main.rs:86:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I get the following error after doing a `bob install stable` and `bob use stable` after the v0.9.0 release.

If I manually specify the 0.9.0 version, it works though.

`bob install 0.9.0` `bob use 0.9.0` works fine.

**Comment by MordechaiHadad** [comment]
@bartdorsey sorry for the inconvenience the github rest api for neovim changed slightly so this caused the issue

**Comment by MordechaiHadad** [comment]
Unfortunately I won't have time to release the hotfix today, so until I do the PR will suffice.
