### ISSUE TITLE
nvim 0.6.1 installs nothing

### ISSUE THREAD

**Issue by wookayin** [MordechaiHadad/bob#127]
Environment: M1 mac (arm64)

```
❯❯❯ bob install 0.6.1

❯❯❯ bob ls              
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
│  v0.8.3   │  Installed  │
│  v0.7.2   │  Installed  │
│  v0.6.1   │  Installed  │
└───────────┴─────────────┘
❯❯❯ ls -alh ~/.local/share/bob/v0.6.1
(nothing)
```

Actually the archive gets extracted at `~/.local/share/bob/nvim-macos`: it seems that a wrong archive layout is assumed for older versions. Other versions like 0.7.2+ are fine.

**Comment by MordechaiHadad** [comment]
@wookayin is `nvim-macos` empty? I made it so that bob will rename a the folder's name to `nvim-macos` from `nvim-osx64`

**Comment by wookayin** [comment]
Yes nvim-macos is the actual content, so manually moved it into v0.6.1.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1009873/231175069-cfed716e-b6b2-41ff-9696-c3d7a72993f7.png">

**Comment by wookayin** [comment]
In addition, v0.6.1/nvim-macos/bin/nvim does not have `+x` permission so I manually needed to `chmod +x`. This might be the issue of nvim release, not of bob.
