### ISSUE TITLE
[Feature Request] A subcommand to update installed `stable/nightly` neovim

### ISSUE THREAD

**Issue by SteveLauC** [MordechaiHadad/bob#133]
I am considering adding `bob` support to [`topgrade`](https://github.com/topgrade-rs/topgrade), to do so, `bob` needs to provide an interface to update the installed `neovim` binaries.

The interface I would to have is:

```shell
$ bob update <stable|nightly> # to update stable or nightly 
$ bob update --all # to update stable and nightly
```

`<version-string>|<commit-hash>` are not involved since they are the exact version the user wants and should not (cannot) be updated.

Any idea on this:)

**Comment by MordechaiHadad** [comment]
@SteveLauC sounds like a good idea, I am kind of busy lately so I won't have much time to implement this but you are free to open a PR you can just add a subcommand that calls the use handler since it can already upgrade those 2
I might look into this project since it looks good

**Comment by SteveLauC** [comment]
Thanks!

I just gave it a try, it is amazing! 


I will add it to `topgrade` tomorrow, thanks for implementing it:)

**Comment by MordechaiHadad** [comment]
that was fast

**Comment by SteveLauC** [comment]
Hi, PR filed:)

https://github.com/topgrade-rs/topgrade/pull/461
