### ISSUE TITLE
Couldn't create downloads directory in non-standard Linux home path

### ISSUE THREAD

**Issue by adwaymalhotra** [MordechaiHadad/bob#134]
It is assumed that the home directory starts with /home/...
https://github.com/MordechaiHadad/bob/blob/7cfe3d1011f64976086e1daf56b674ee9bd269f2/src/helpers/directories.rs#L25

That is not always the case. I think bob should check if the directory exists before returning, and should fall back to the HOME variable if it doesn't exist.

**Comment by MordechaiHadad** [comment]
Bob already resorts to $HOME if both $USER or $SUDO_USER don't exit

**Comment by MordechaiHadad** [comment]
@adwaymalhotra I have pushed a new commit, can you check if it works now
download the exe through the github action. https://github.com/MordechaiHadad/bob/actions/runs/5044905332

**Comment by adwaymalhotra** [comment]
Thanks for the change! I've tried the artifact from your link and it seems to work fine! At the same time, the version that I installed from cargo fails with the error I mentioned earlier, so it seems we have a fix!

**Comment by MordechaiHadad** [comment]
@adwaymalhotra ye if you install via cargo you will need to use the git link, glad it's fixed
