### ISSUE TITLE
Create homebrew formula?

### ISSUE THREAD

**Issue by baggiponte** [MordechaiHadad/bob#143]
Are you interested in a homebrew formula? e.g. install `bob` on macOS with `brew install bob-nvim` as an alternative to `cargo`. It is pretty straightforward, though you might want to add a CI/CD step to automatically update the formula when you make a new release. Some more details about how to do this for a rust-based project are [here](https://github.com/max-niederman/ttyper/issues/87#issuecomment-1596208046).

**Comment by MordechaiHadad** [comment]
sounds like a good idea, unfortunately I am a bit too busy with other projects.
If you want you can create a PR to do it until I manage to learn and do it

**Comment by baggiponte** [comment]
Would love to! I should have time to work on a draft PR by the weekend.

**Comment by MordechaiHadad** [comment]
awesome! could you elaborate a bit on how homebrew repos work exactly? in Arch linux user repo(AUR) you have to  create an account, create a repo with the specification of the package and push it to the repo

**Comment by tnxz** [comment]
any update on this brew formula yet

**Comment by MordechaiHadad** [comment]
I plan on adding it, but I barely get the time to do so.

**Comment by tnxz** [comment]
sure thanks for the heads up

**Comment by baggiponte** [comment]
My bad too, barely have time. I am still interested, if you don't mind the waiting I'll gladly take it.

**Comment by Subjective** [comment]
Just wanted to point out that you can also have homebrew automatically setup shell completions (see [zoxide](https://github.com/Homebrew/homebrew-core/blob/master/Formula/z/zoxide.rb) or [rtx](https://github.com/Homebrew/homebrew-core/blob/master/Formula/r/rtx.rb) for examples).

**Comment by MordechaiHadad** [comment]
> I too thought it could be complex. Turns out, it is quite easy:
> 
> Here's what I went through as macOS user:
> 
>     1. Fork [homebrew-core](https://github.com/Homebrew/homebrew-core).
> 
>     2. Toggle `brew developer on`. This will activate homebrew "developer mode", i.e. homebrew is just a [GH repo](https://github.com/Homebrew/homebrew-core): now when you run brew update you will trigger a git pull in your local clone from the master branch.
> 
>     3. Run `brew update`.
> 
>     4. Run `cd (brew --repository homebrew/core)` to cd into the repo.
> 
>     5. Create a new branch
> 
>     6. Add my fork as a remote repo
> 
>     7. Run `brew create --set-name=bob-nvim --rust https://github.com/MordechaiHadad/bob/archive/refs/tags/v2.4.1.tar.gz`
>        The URL is the url of the latest version of bob that I got from [bob tags page](https://github.com/MordechaiHadad/bob/archive/refs/tags)
> 
>     8. Commit and push to my fork.
> 
>     9. Open a PR to homebrew/core to have your formula reviewed (I guess) and merged.
> 
> 
> Some more details are at the url I referenced at the top ([here](https://github.com/max-niederman/ttyper/issues/87#issuecomment-1596208046) too) which is a comment on a similar issue I opened in `ttyper`. The only hassle I see with maintaining a homebrew formula is to create a CI/CD workflow to bump the version in the formula itself (the one generated at step 7) and open a similar PR. Depends on how often you plan to release.

Do I have to use macOS for this?

**Comment by Amar1729** [comment]
Hey all, went ahead and made a PR for adding this to homebrew.

@MordechaiHadad fyi, you can make contributions to Homebrew from linux (as `brew` supports installing formulae on Linux as well) but depending on the package it can feel more streamlined on macOS.

**Comment by MordechaiHadad** [comment]
@Amar1729 thats awesome thank you

**Comment by Amar1729** [comment]
Merged 👍 (i can submit a minor update with instructions to the README in a bit)

FWIW, there is a [`bump-formulae`](https://github.com/Homebrew/actions/tree/master/bump-formulae) GitHub Action that could be used by this repo's CI workflows on release to automatically submit PRs to homebrew, but I'm not as familiar with using it. Also not sure if it's worth it, depending on how frequently new releases happen.

**Comment by MordechaiHadad** [comment]
Thanks awesome thank you for your work, regarding GH action idk if it's necessary at this point bob is complete-ish so releases are a lot slower now

**Comment by baggiponte** [comment]
Thanks @Amar1729! Just installed bob with brew and it went smoothly. Guess we can close this issue!

**Comment by MordechaiHadad** [comment]
@Amar1729 what does one have to change in the formula file to indicate an update?

**Comment by Amar1729** [comment]
@MordechaiHadad if nothing changes about the build or test process, generally you only need to change the `url` and `sha256`. Homebrew's CI will update the `bottles` stanza for you during merge.

**Comment by MordechaiHadad** [comment]
> @MordechaiHadad if nothing changes about the build or test process, generally you only need to change the `url` and `sha256`. Homebrew's CI will update the `bottles` stanza for you during merge.

Oh okay, how do you regenerate new `sha256` hashes though?

**Comment by Amar1729** [comment]
> how do you regenerate new `sha256` hashes

There are a couple ways.

1. In practice, what I frequently do is change _just_ the url, then (on my local machine), run `brew install <whatever>`. Homebrew will download the .tar.gz, then warn that the hash doesn't match along with the actual value. Then I just copy the actual value in to the formula file, rerun `brew install` to test, and make a commit+pr.

2. There is probably a "better" way to do it with `brew bump-formula-pr`, which i think is something like `brew bump-formula-pr --dry-run --url <url>` (and `brew` will try to determine the new hash if not given?)

3. If you don't have brew installed locally, you could simply download the .tar.gz from a release yourself and check the hash (e.g. `sha265sum whatever.tar.gz`).

If you want to do it from within CI, there might be a homebrew action you can use? if not, you would simply do something like (2) in a new manually defined action step using brew (can be installed on macOS or linux) and pass the url from a new release that's been made by a previous CI step

**Comment by MordechaiHadad** [comment]
> > how do you regenerate new `sha256` hashes
> 
> There are a couple ways.
> 
>     1. In practice, what I frequently do is change _just_ the url, then (on my local machine), run `brew install <whatever>`. Homebrew will download the .tar.gz, then warn that the hash doesn't match along with the actual value. Then I just copy the actual value in to the formula file, rerun `brew install` to test, and make a commit+pr.
> 
>     2. There is probably a "better" way to do it with `brew bump-formula-pr`, which i think is something like `brew bump-formula-pr --dry-run --url <url>` (and `brew` will try to determine the new hash if not given?)
> 
>     3. If you don't have brew installed locally, you could simply download the .tar.gz from a release yourself and check the hash (e.g. `sha265sum whatever.tar.gz`).
> 
> 
> If you want to do it from within CI, there might be a homebrew action you can use? if not, you would simply do something like (2) in a new manually defined action step using brew (can be installed on macOS or linux) and pass the url from a new release that's been made by a previous CI step

Anyway I can do it on windows? my WSL arch installed is fucked.

**Comment by Amar1729** [comment]
Hm - not sure how to check hashes of filles on win of the top of my head but I'd assume there's a powershell cmdlet/windows command to get the hash of a file? If not, could probably just look up "sha256 hash site"? After that, it really is just a change to two lines of a ruby file in a git repo.

**Comment by MordechaiHadad** [comment]
@Amar1729 what was that CI u mentioned

**Comment by Amar1729** [comment]
@MordechaiHadad I could draw up an outline for the ci in a new issue to avoid pinging everyone subscribed to this one
