### ISSUE TITLE
add github proxy config

### ISSUE THREAD

**Issue by damingerdai** [MordechaiHadad/bob#144]
it is hard for Chinese user to visit github sometime. so we use github proxy like [ghproxy](https://ghproxy.com/) to help us to visit.
it is possible to add github proxy config to help the user who can not visit github easy?

**Comment by MordechaiHadad** [comment]
please elaborate on this further, my ISP blocks this website so I can't really do anything related to it

**Comment by damingerdai** [comment]
for example;

sometime, you can not visit github:

```bash
git clone https://github.com/MordechaiHadad/bob.git
```
it will be in failed because we can't visit github.

so you can try to use ghproxy

```bash
git clone https://ghproxy.com/https://github.com/MordechaiHadad/bob.git
```

it is real hard for no Chinese user to understand
