### ISSUE TITLE
Q: is it possible to use `update-alternatives` with bob?

### ISSUE THREAD

**Issue by rsb177** [MordechaiHadad/bob#150]
Normally, i change my default editor via update-alternatives to neovim.  I decided to try using bob to manage neovim for me, but when I tried setting vi to the nvim executable from bob, it acts like I just ran `bob` instead.  Is there a way to do this via update-alternatives, or should i just alias instead?

**Comment by MordechaiHadad** [comment]
I have no idea what's update-alternatives

**Comment by rsb177** [comment]
basically, a way to manage things like which editor I want to use when I type `vi`.
[Man Page](https://www.unix.com/man-page/Linux/8/update-alternatives/)
[Overview](https://www.baeldung.com/linux/update-alternatives-command)

**Comment by MordechaiHadad** [comment]
I see, can you show me how you set it up?
Bob uses a proxy executable, if you rename bob to nvim it will execute neovim rather than bob.

**Comment by rsb177** [comment]
I just ran `sudo update-alternatives --install /usr/bin/vi vi /home/rsb177/.local/share/bob/nvim-bin/nvim 100`.  It looks like since it's a proxy executable, if I set up a symbolic link to it (as any name other than `nvim`), it'll always run `bob`.  Was able to replicate this by just using simple symbolic links.  So it looks like I'll need to stick with just using aliases if I want to use nvim for commands like `vi`, `view`, etc.

**Comment by MordechaiHadad** [comment]
@rsb177 what name does the update-alternatives gives the executable?

**Comment by rsb177** [comment]
in the case of the command above, it shows up as `vi`

**Comment by pjgoodall** [comment]
a worked example for vim / nvim https://thomasventurini.com/articles/how-to-use-update-alternatives/

I used update-alternatives, and somehow bob has replaced vim
