### ISSUE TITLE
[outline] Update CI to bump Homebrew formula

### ISSUE THREAD

**Issue by Amar1729** [MordechaiHadad/bob#162]
as mentioned over in #143

You could update your GitHub Actions to also have a "release" job that submits a PR to homebrew automatically when you bump bob's version. 

1. create a new action (conventionally called "release"). usually this action would only run on tags
2. this action could extend https://github.com/softprops/action-gh-release to upload new binaries to GitHub releases (but for homebrew, all you need is the source code .tar.gz)
3. extend https://github.com/Homebrew/actions/tree/master/bump-formulae to run `brew bump-formulae` in a macOS environment. this will use your new github release URL and automatically submit a PR to homebrew upstream with the new version

step 3 will need an access token set up because it'll be making a commit for an external (homebrew/homebrew-core) repo. 

not sure if I can get around to actually testing this anytime soon so somebody else can get free to implement it.

**Comment by MordechaiHadad** [comment]
Oh that's cool, tbh I didn't even bother with GH releases maybe I should now

**Comment by Amar1729** [comment]
FWIW i think homebrew generally prefers to install things from Github releases, so could be good to at least push tags for releases.

As far as the CI, might not actually be worth it to you to automate the whole thing if releases are relatively infrequent ([relevant xkcd](https://xkcd.com/1205/))

**Comment by MordechaiHadad** [comment]
🤔 so how should i go about doing this, since i dont really have access to getting those hashes from a formula

**Comment by MordechaiHadad** [comment]
I'll setup those just for the sake of learning and future projects, ig,

**Comment by Amar1729** [comment]
> 🤔 so how should i go about doing this, since i dont really have access to getting those hashes from a formula

I'm pretty sure `brew bump-formulae <url>` will attempt to auto-determine the sha256 (which is the only one you need) of the given URL. So for example, you might call it from within a github action after the release has been published, at which point you could pass the URL of the newly-tagged release's .tar.gz. Then (within the workflow) `brew bump-formulae` would presumably download that .tar.gz, calculate the sha256 for you, then auto-commit and make the pull request to homebrew-core for you (i'm a bit fuzzy on the last step as i've never done it myself)

**Comment by MordechaiHadad** [comment]
> > 🤔 so how should i go about doing this, since i dont really have access to getting those hashes from a formula
> 
> I'm pretty sure `brew bump-formulae <url>` will attempt to auto-determine the sha256 (which is the only one you need) of the given URL. So for example, you might call it from within a github action after the release has been published, at which point you could pass the URL of the newly-tagged release's .tar.gz. Then (within the workflow) `brew bump-formulae` would presumably download that .tar.gz, calculate the sha256 for you, then auto-commit and make the pull request to homebrew-core for you (i'm a bit fuzzy on the last step as i've never done it myself)

Oh this is cool

**Comment by MordechaiHadad** [comment]
What exactly is this part in `bump-formulae`:
```yaml
    formulae: |
      FORMULA-1
      FORMULA-2
      FORMULA-3
 ```

**Comment by Amar1729** [comment]
That's a constraint on which specific formulae to bump. so you could write just `bob`

**Comment by MordechaiHadad** [comment]
so just:
```yaml
formulae: bob
```
?

**Comment by MordechaiHadad** [comment]
@Amar1729  So basically all i have to put in this is just:
```yaml
- name: Bump formulae
  uses: Homebrew/actions/bump-formulae@master
  with:
    # Custom GitHub access token with only the 'public_repo' scope enabled
    token: ${{secrets.TOKEN}}
    # Bump only these formulae if outdated
    formulae: |
      FORMULA-1
      FORMULA-2
      FORMULA-3
 ```
 This is either too easy or the docs kinda suck

**Comment by Amar1729** [comment]
@MordechaiHadad lol, I think so? but you'll also want a thing right before that that creates the release of you didn't do that already

**Comment by MordechaiHadad** [comment]
> @MordechaiHadad lol, I think so? but you'll also want a thing right before that that creates the release of you didn't do that already

Ye working on that, want to make sure the release CD I am gonna make is sync so first it uploads release and then it runs the bump formulae thing

**Comment by MordechaiHadad** [comment]
@Amar1729 review #167 if it seems fine to you

**Comment by MordechaiHadad** [comment]
https://github.com/MordechaiHadad/bob/actions/runs/6995199206/job/19029858968
Currently its already past 10 minutes 🤣

**Comment by MordechaiHadad** [comment]
2 hours now jesus

**Comment by Amar1729** [comment]
Huh ... well that's not good, lmao

**Comment by Amar1729** [comment]
Alternatively, could remove the `homebrew` step; the maintainers + top contributors to homebrew-core are usually pretty quick about updating the formulae in core already https://github.com/Homebrew/homebrew-core/pull/155610

**Comment by MordechaiHadad** [comment]
Oh shit epic contributors, I'd still try the other bump formula next release.
