### ISSUE TITLE
need a symbolic link to the manual of the used version to support update-alternatives

### ISSUE THREAD

**Issue by pjgoodall** [MordechaiHadad/bob#168]
Amongst the Debians, when setting `update-alternatives` the `--slave`  parameter can't be set in a way that isn't broken when `bob use xx` changes the version of nvim. If we had a `man1` directory under `~/.local/share/bob`, it would all work nicely.

see [baeldung - update-alternatives command](https://www.baeldung.com/linux/update-alternatives-command) 

And - thanks very much for your very useful utility - nvim under Ubuntu is a mess...

**Comment by MordechaiHadad** [comment]
Still not very sure what I am supposed to do with this `man1` dir

**Comment by MordechaiHadad** [comment]
🤔

**Comment by pjgoodall** [comment]
I leave where you put the manual file up to you. You may know better than me. But for bob to install a new version of nvim and its manual, and for them to be useful with update-alternatives, they need to be linked to a stable location.  I thought a man directory would be conventional. The manuals for vim seem to find themselves in /usr/share/man1 
The tutorial i linked to explains how the --slave option uses the man location. If I use your current place for the man, I will have to relink --slave every time I used bob to change the version of nvim.

I don't know what else to say.  Except thanks for your time, and the excellent utility.

**Comment by pjgoodall** [comment]
Yes thanks.

**Comment by MordechaiHadad** [comment]
test #174 via one of the provided artifacts before i merge this

**Comment by MordechaiHadad** [comment]
@pjgoodall is this still relevant?

**Comment by pjgoodall** [comment]
@MordechaiHadad 
My apologies. I’ll check it asap. 
Many thanks.

**Comment by pjgoodall** [comment]
@MordechaiHadad 

`man nvim` does not work after `bob use latest`, and adding `bob/nvim-bin` in `.zshrc` to the path - this is independent of the update-alternatives mechanism. Maybe there needs to be a script , or an init inclusion in the  .zshrc 

I tried testing against `cargo install --branch feat/man-copying --git https://github.com/MordechaiHadad/bob.git` again. I detect see any difference. Did I try the right install?

There seem to be a lot of initialization scripts about (from my .zshrc):
``` shell
source $OH_MY_ZSH/oh-my-zsh.sh
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
source ${ZPLUG_HOME}/init.zsh
# Then, source plugins and add commands to $PATH
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source ${ZSH_ALIAS_FILE}
source ${XDG_CONFIG_HOME}/broot/launcher/bash/br
[ -f "${HOME}/.ghcup/env" ] && source "${HOME}/.ghcup/env" # ghcup-env
source ${XDG_CONFIG_HOME}/broot/launcher/bash/br
source <(jj util completion zsh)
 source ${XDG_CONFIG_HOME}/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
I'm sorry I can't help with the work - I've never programmed in rust.

Cheers...

**Comment by MordechaiHadad** [comment]
What was the message you got from running `bob use latest`?

**Comment by pjgoodall** [comment]
The target system:
```
bob-nvim% lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
I used the command-line to install:
``` shell
cargo git https://github.com/MordechaiHadad/bob.git#feat\/man-copying
```

```shell
/home/peterg/.cargo/bin/bob
bob-nvim% bob --version
bob-nvim 2.8.3
bob-nvim% bob use latest
Apr 02 02:42:48.554  INFO Fetching latest version
Downloaded version v0.9.5 to /home/peterg/.local/share/bob/v0.9.5.appimage
  [00:00:01] [███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 10.66MiB/10.66MiB (6.00MiB/s, 0s)
Apr 02 02:42:51.939  INFO You can now use v0.9.5!
```

The manual file is installed:
```shell
bob-nvim% fd -H nvim.1
.local/share/bob/v0.9.5/nvim-linux64/man/man1/nvim.1
```

**Comment by MordechaiHadad** [comment]
It seems like you need to add `enable_manpage_mirror` to your bob config and set it to true

**Comment by pjgoodall** [comment]
So sorry- will test tomorrow. Thanks for reminding me 🤦‍♂️

**Comment by pjgoodall** [comment]
``` zsh
bob-nvim% echo $BOB_CONFIG 
  /home/peterg/.config/bob/config.toml
bob-nvim% cat $BOB_CONFIG 
  enable_manpage_mirror=true
bob-nvim% fd -H nvim.1
  .local/share/bob/v0.10.0/nvim-linux64/share/man/man1/nvim.1
  ```

I can't see anywhere there is a stable link to the manual
installed from `https://github.com/MordechaiHadad/bob.git#feat\/man-copying`

**Comment by MordechaiHadad** [comment]
> ```shell
> bob-nvim% echo $BOB_CONFIG 
>   /home/peterg/.config/bob/config.toml
> bob-nvim% cat $BOB_CONFIG 
>   enable_manpage_mirror=true
> bob-nvim% fd -H nvim.1
>   .local/share/bob/v0.10.0/nvim-linux64/share/man/man1/nvim.1
> ```
> 
> I can't see anywhere there is a stable link to the manual installed from `https://github.com/MordechaiHadad/bob.git#feat\/man-copying`

Have you switched any versions during this experiment using `bob use xxx`? it will only copy on use command.
