### ISSUE TITLE
[Question] Does bob attempt to update runtime files?

### ISSUE THREAD

**Issue by alexmozaidze** [MordechaiHadad/bob#173]
I've encountered an issue similar to [this one](https://github.com/nvim-treesitter/nvim-treesitter/issues/1499), and fixing it suggests doing `make clean`. So now, I wonder: does bob update the runtime files on each new `bob use`?

**Comment by MordechaiHadad** [comment]
What do you mean exactly by new `bob use` like whenever you install new neovim version with bob?

**Comment by alexmozaidze** [comment]
Yes

**Comment by MordechaiHadad** [comment]
Well, bob simply downloads and installs the archive for each release they provide, so if they did then the runtime files are updated.
But no, bob doesn't update them directly.
