### ISSUE TITLE
Runtime files won't be detected on Windows

### ISSUE THREAD

**Issue by lopi-py** [MordechaiHadad/bob#178]
I'm using the latest bob release 2.7.0
```
bob install nightly
bob use nightly
nvim -u NONE
```
```
:lua print(vim.lsp)
```
![image](https://github.com/MordechaiHadad/bob/assets/70210066/8b341ac3-0adf-4af7-a470-30da8b45bed1)
I think it's because bob is not updating $VIMRUNTIME (I had to set it manually to `C:\Users\HP\AppData\Local\bob\v0.9.5\nvim-win64\share\nvim\runtime`)

**Comment by lopi-py** [comment]
I'm getting this when I use `vim.loader.enable()`
![image](https://github.com/MordechaiHadad/bob/assets/70210066/d944e19f-acec-4785-ac39-c06aa4817111)
And also nvim crashes when I call `require("lazy").setup`. I know those aren't bob problems but that doesn't occur if I use non-managed bob nvim, chocolatey for example works fine.

**Comment by MordechaiHadad** [comment]
I can't recreate this issue, i downloaded neovim binary directly from github releases (how bob does it) made sure `$VIMRUNTIME` doesn't exist (I also checked chocolatey installation files for both neovim and vim) and ran the commands you mentioned got no errors.

https://github.com/MordechaiHadad/bob/assets/33547558/95d8effa-a34c-409e-be96-9a0860745a92

**Comment by lopi-py** [comment]
I'll try to get repro steps, I don't know why bob doesn't work whereas chocolatey does. I'll try with a manual neovim install too.

**Comment by MordechaiHadad** [comment]
> I'll try to get an actual repro, I don't know why bob doesn't work whereas chocolatey does. I'll try with a manual neovim install too.

Alright i could try reproducing also on my laptop

**Comment by lopi-py** [comment]
Ok its working now, I just deleted `VIMRUNTIME`.
