### ISSUE TITLE
Does bob clean old nightly build caches?

### ISSUE THREAD

**Issue by linrongbin16** [MordechaiHadad/bob#179]
Hi, the `bob list` shows:

<img width="304" alt="image" src="https://github.com/MordechaiHadad/bob/assets/6496887/aa2a7f94-ddf1-4a63-b907-cf05ef30de37">

Does bob stores multiple nightly caches?

**Comment by MordechaiHadad** [comment]
This is odd, bob should remove nightly rollbacks when they go above 3, show me your bob config. also I suggest you just remove the oldest rollbacks (listed by age when doing bob rollback) and report back when this persists.

**Comment by linrongbin16** [comment]
emmmm, I didn't config bob, and based on this section:  https://github.com/MordechaiHadad/bob?tab=readme-ov-file#-configuration.

I don't have directory named: `~/Library/Application\ Support/bob`, I'm using macbook pro.

<img width="147" alt="image" src="https://github.com/MordechaiHadad/bob/assets/6496887/2b6f1031-fffe-4199-8405-cedef12cc7fa">

<img width="648" alt="image" src="https://github.com/MordechaiHadad/bob/assets/6496887/dd01c073-9993-41fb-804c-5b65ca0cc036">

**Comment by MordechaiHadad** [comment]
I see, could you make a toml/json file somewhere with `rollback_limit` set 3 three and set the file location via `BOB_CONFIG` env var? (but that would matter if you create a new rollback which you probably wont for a day)

**Comment by linrongbin16** [comment]
I suddenly find that `bob erase` will remove all installed versions, so it's cleaned all caches for me. I just re-installed the stable version:

<img width="361" alt="image" src="https://github.com/MordechaiHadad/bob/assets/6496887/e1629446-eba3-4013-9025-56b88d225e89">

BTW, the `config.json` and `rollback_limit=3` seems not working for me, I set them but caches still exists.

**Comment by MordechaiHadad** [comment]
> I suddenly find that `bob erase` will remove all installed versions, so it's cleaned all caches for me. I just re-installed the stable version:
> <img alt="image" width="361" src="https://private-user-images.githubusercontent.com/6496887/294454698-e1629446-eba3-4013-9025-56b88d225e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjQ1OTcsIm5iZiI6MTcwNDQ2NDI5NywicGF0aCI6Ii82NDk2ODg3LzI5NDQ1NDY5OC1lMTYyOTQ0Ni1lYmEzLTQwMTMtOTAyNS01NmI4OGQyMjVlODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTQxODE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdmMTMwYWRhMzJlYWMzNTU0ZGYwNTBmNzMzMWVkOTdhNzc1NGNiNWEwOTJmMjI0ODI5MGY3NzZkOWZjNTcyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p1d9Pt6qb7eqvTDukd3kFlY3cnFPk64BDY1pxCaQ2-w">
> 
> BTW, the `config.json` and `rollback_limit=3` seems not working for me, I set them but caches still exists.

Ye it's not meant to remove rollbacks when using bob, but only when installing a new nightly version which is why i suggested you remove them yourself.

**Comment by MordechaiHadad** [comment]
@linrongbin16 Report back to this issue if you actually get this issue again.
