### ISSUE TITLE
error trying to install any version of nvim via bob

### ISSUE THREAD

**Issue by rdataforge** [MordechaiHadad/bob#185]
HI

After installing bob on WSL2 - ubuntu via command line ` cargo install bob-nvim`  I try to install stable version with:
` bob install stable`
but i get an error 

`error trying to connect: invalid peer certificate: UnknownIssuer`

any help will be much appreciated

**Comment by MordechaiHadad** [comment]
Are you using something like a VPN or a business network?

**Comment by rdataforge** [comment]
I assume that is maybe the issue, something called zscaler

**Comment by MordechaiHadad** [comment]
> hmmm, would be better if u elaborate further

@rdataforge still waiting for that, without much information I have no idea how to proceed with this issue.

**Comment by rdataforge** [comment]
Apart from confirming with my IT department the existence of such Zscaler-thing, i do not know how could i help

**Comment by MordechaiHadad** [comment]
more than likely fixed with #227
