### ISSUE TITLE
Can install, but cannot use neovim

### ISSUE THREAD

**Issue by kurt-rhee** [MordechaiHadad/bob#197]
I am able to download bob
I can download the latest version of neovim
I cannot use the latest version of neovim
I am using Ubuntu 22.04

bob ls indicates that the versions are installed
![image](https://github.com/MordechaiHadad/bob/assets/33131958/a7ea0663-9d39-4100-b4e1-a8a574973f49)
![image](https://github.com/MordechaiHadad/bob/assets/33131958/2b19612d-9f44-436b-9c41-f16c0aa07e85)

I have added bob to my path
![image](https://github.com/MordechaiHadad/bob/assets/33131958/5d6a9b33-1735-486d-9ad9-1cae4bde6346)

I have also tried:
![image](https://github.com/MordechaiHadad/bob/assets/33131958/667c7e6b-a536-4961-9bcd-dbfb5e3715d1)

Each time I use source ~/.bashrc to update my bashrc.

**Comment by mikesmithgh** [comment]
I just saw this as well. I installed bob on a completely fresh install of Ubuntu.

![no-bob-error](https://github.com/MordechaiHadad/bob/assets/10135646/e4aba1bb-90b4-4d82-bda7-7a8346066fe0)

It looks like when there is no existing `nvim` in the `~/.local/share/bob/nvim-bin/` it will throw this error.

FYI @kurt-rhee I worked around this by manually copying `nvim` from `~/.local/share/bob/nightly/nvim-linux64/bin` to `~/.local/share/bob/nvim-bin/`.

After that, all works as expected.

**Comment by MordechaiHadad** [comment]
Hello apologies for the faulty release (did not take this edge case in consideration), could you test PR #199 ?

The following steps to follow in order to test:
1. Uninstall bob from your system
2. Reinstall the branch with: `cargo install --git https://github.com/MordechaiHadad/bob --branch fix/nvim-proxy`
3. Run `bob erase`
4. And then `bob use nightly`
5. And try to run neovim.

**Comment by MordechaiHadad** [comment]
@mikesmithgh @kurt-rhee could you guys verify the PR fixes this?

**Comment by kurt-rhee** [comment]
Hey @MordechaiHadad thanks for the quick response.  I work in Pacific time, so may not be able to give timely responses, but I was able to try the fix/nvim-proxy branch and everything is working on my side.

![image](https://github.com/MordechaiHadad/bob/assets/33131958/ead72900-71b8-4ff2-95d1-a17f8f3c1c56)

**Comment by MordechaiHadad** [comment]
> Hey @MordechaiHadad thanks for the quick response.  I work in Pacific time, so may not be able to give timely responses, but I was able to try the fix/nvim-proxy branch and everything is working on my side.
> 
> ![image](https://github.com/MordechaiHadad/bob/assets/33131958/ead72900-71b8-4ff2-95d1-a17f8f3c1c56)
> 

All good, neovim launches correctly?
