### ISSUE TITLE
Compiles Debug build on Windows, but RelWithDebugInfo on Linux

### ISSUE THREAD

**Issue by sid-6581** [MordechaiHadad/bob#203]
When I run `bob use <commit>`, on both Windows and Linux, the Linux build is correctly built as `RelWithDebugInfo`, but the Windows build is `Debug`.

**Comment by MordechaiHadad** [comment]
Yes at the time I added building from source I didn't really know how to set it as Release with debug info for windows since it doesn't use cmake, maybe it's time to know how to do this.

**Comment by MordechaiHadad** [comment]
@sid-6581 can you confirm this works?

**Comment by sid-6581** [comment]
> @sid-6581 can you confirm this works?

Unfortunately that didn't work, since `-D` isn't a valid option for `--build`. Let me try to get it to work and I'll give you the code I have so you can modify the PR you already have.
