### ISSUE TITLE
bug: terminates on usr1 signal

### ISSUE THREAD

**Issue by sarmong** [MordechaiHadad/bob#209]
Neovim supports `Signal` autocommand. However, when the signal is sent to the neovim instance installed with bob, neovim terminates with 138.

This doesn't happen when neovim is built from source, or via official appimage.

To reproduce:

1. `bob use latest` (the same with nightly)
2. `kill -USR1 $(pgrep nvim)`
3. nvim terminates and the terminal is messed up

Happens on Debian 12

**Comment by MordechaiHadad** [comment]
Yes it's a problem with bob itself (maybe rust doesn't handle SIGUSR1). I will look into this but might take a while since Rust doesn't kill subprocesses with SIGTERM which will take some time to figure out unless I used a bit dep like nix crate.

Side note: for windows users there isn't really anything to do regarding this since windows TerminateProcess is not something that can be caught and handled.

**Comment by MordechaiHadad** [comment]
@sarmong Could you test the PR?

**Comment by sarmong** [comment]
Neovim still terminates, however now the terminal (or is it shell) is not messed up after termination

**Comment by MordechaiHadad** [comment]
It is meant to terminate, so it works.

**Comment by sarmong** [comment]
No, it is not. This is USR1 signal, not INT. Any other version version of nvim (from source, .deb, .appimage) doesn't terminate.

**Comment by MordechaiHadad** [comment]
Oh, I thought the expected behavior was not the fucked up terminal which was caused by SIGKILL so I simply changed it to SIGTERM, is the expected behavior is to keep working basically?

**Comment by sarmong** [comment]
Yes. Neovim can catch USR1 via [`Signal` autocommand](https://neovim.io/doc/user/autocmd.html#Signal), but it is not possible when opening bob version of neovim.

**Comment by MordechaiHadad** [comment]
Updated the PR let me know if this is the behavior u expected. (cant really test this, since I am on windows)

**Comment by sarmong** [comment]
Works properly now, thanks!
