### ISSUE TITLE
[Feature] bob erase - do not delete non empty installation_location directory

### ISSUE THREAD

**Issue by kisuryoza** [MordechaiHadad/bob#211]
Currently `bob erase` erases directories associated with bob.

When in config user sets `installation_location = /home/user/.local/bin` in order to have `nvim` among with other user's binaries, he does not expect the whole `bin` directory to be erased.

I suggest that after `bob erase`, only `nvim` should be deleted if the directory it is in is not empty. Or ask the user for confirmation of deleting the whole directories.

**Comment by MordechaiHadad** [comment]
@kisuryoza created a new PR, could you test it and tell me if this is what u wanted?

**Comment by kisuryoza** [comment]
No but here's what I wanted #220.

**Comment by MordechaiHadad** [comment]
hmm let me understand one thing, why exactly would you prefer not deleting? bob creates `bob-nvim` sub directory under installation directory. and bob erase is supposed to erase everything bob related.

So why not erase the sub directory instead of not deleting it.

**Comment by kisuryoza** [comment]
For the default `installation_location` there are no problems. But if I set `installation_location = /home/user/.local/bin` in `config.toml`, `bob use ***` will put the executable inside `/home/user/.local/bin` among my other files as I want.
And `bob erase` deletes the entire `/home/user/.local/bin`, what I didn't expect, loosing files I didn't want to.

If the current behavior is preferable it would be better to ask a user for confirmation of deleting the whole `installation_location`.

**Comment by MordechaiHadad** [comment]
@kisuryoza better now?

**Comment by kisuryoza** [comment]
Yes.

**Comment by MordechaiHadad** [comment]
@kisuryoza done

**Comment by kisuryoza** [comment]
Now it's all working as I requested.
