### ISSUE TITLE
Install based on nvim --version

### ISSUE THREAD

**Issue by erlonbie** [MordechaiHadad/bob#213]
This is probably a noob question, but I could not find a proper answer for this.

Context:

When I type **nvim -- version**, I get this ouput:

```powershell
NVIM v0.10.0-dev-1911+g104565909
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run "nvim -V1 -v" for more info
```

For **bob list**:

```powershell
┌────────────────────┬─────────────┐
│  Version           │  Status     │
├────────────────────┼─────────────┤
│  nightly           │  Used       │
│  v0.9.2            │  Installed  │
│  nightly-SLg7CqfG  │  Installed  │
│  nightly-qYnEB3PP  │  Installed  │
└────────────────────┴─────────────┘
```

I decide to install/use the stable version and my **bob list** output became this:

```powershell
┌────────────────────┬─────────────┐
│  Version           │  Status     │
├────────────────────┼─────────────┤
│  nightly           │  Installed  │
│  v0.9.2            │  Installed  │
│  nightly-SLg7CqfG  │  Installed  │
│  v0.10.0           │  Used       │
│  nightly-qYnEB3PP  │  Installed  │
└────────────────────┴─────────────┘
```

The problem is that if try to return to nightly using the `use` command version, it will automatically update and go to (probably) to 0.11.0 which will break my current config.

What I would like to know is how to install based on that version number that is already installed, in this case **NVIM v0.10.0-dev-1911+g104565909**

I search on the main branch (which is the dev branch) of neovim a commit that contains the **g104565909** but could not find it.

I'm probably missing something, but at the moment I'm out of ideas. Thanks in advance!

**Comment by MordechaiHadad** [comment]
Bob automatically creates rollbacks upon nightly update, in your instance `nightly-qYnEB3PP`, `nightly-SLg7CqfG` if you want to rollback to the latest nightly, simply run `bob rollback` and choose the first option.
