### ISSUE TITLE
certificate error installing nvim latest using bob in ubuntu wsl

### ISSUE THREAD

**Issue by verajosemanuel** [MordechaiHadad/bob#215]
when trying to install latest version in ubuntu WSL i get an odd message:

![image](https://github.com/MordechaiHadad/bob/assets/15836677/51bfa40b-9696-4c42-a63d-bb1e4f0896c3)

**Comment by MordechaiHadad** [comment]
@verajosemanuel Are you on a work network or something? That or VPNs usually cause this issue.

**Comment by reverendpaco** [comment]
I have been getting the same thing recently.  Bob used to work perfectly.  I upgraded to the v2.9.1 bob, but still the same issue.  Almost definitely a work VPN (although bob worked when I first installed it).

**Comment by verajosemanuel** [comment]
Definitely a work VPN could be the issue

**Comment by MordechaiHadad** [comment]
@verajosemanuel Do you know where is your custom ca certificate is located at? I could add support for setting an env variable that will load the ca file when the var is present.

**Comment by ElPapiMango** [comment]
I got the same issue. Curl works fine though. I don't use a custom location but added the certs to the main location. But bob is not working.

* processing: https://objects.githubusercontent.com/github-production-release-asset-2e65be/16408992/b1c65236-e281-4582-befc-5479862f9dac?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240716T164504Z&X-Amz-Expires=300&X-Amz-Signature=4d3308b03b7dfcd87dadd655f4648fcb006d157388d64c649dca062d498b67cb&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=16408992&response-content-disposition=attachment%3B%20filename%3Dnvim.appimage&response-content-type=application%2Foctet-stream
* Uses proxy env variable https_proxy == 'http://192.168.127.254:9000'
*   Trying 192.168.127.254:9000...
* Connected to 192.168.127.254 (192.168.127.254) port 9000
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Establish HTTP proxy tunnel to objects.githubusercontent.com:443
> CONNECT objects.githubusercontent.com:443 HTTP/1.1
> Host: objects.githubusercontent.com:443
> User-Agent: curl/8.2.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection Established
< Proxy-Agent: Zscaler/6.2
<
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):

**Comment by ElPapiMango** [comment]
Change this in cargo.toml and it worked ¯\_(ツ)_/¯
```
[features]
default = ["rustls-tls"]
native-tls = ["reqwest/default-tls"]
#rustls-tls = ["reqwest/rustls-tls"]
rustls-tls = ["reqwest/rustls-tls-native-roots"]
```

**Comment by MordechaiHadad** [comment]
@verajosemanuel let me know if this also fixes your issue like @ElPapiMango
