### ISSUE TITLE
Add Darwin ARM build for M1 devices

### ISSUE THREAD

**Issue by Allaman** [MordechaiHadad/bob#22]
I think the title says it all :) 

I would appreciate a native Darwin ARM version of this awesome tool

**Comment by MordechaiHadad** [comment]
Great timing lol i was just looking into this!

**Comment by MordechaiHadad** [comment]
Hello so after looking up online regarding ARM compilation, this will sadly have to wait some time...
Until either github actions or https://github.com/cross-rs/cross have M1 support I'm going to to wait.
I also plan on adding ARM Linux support and I could manage it now, but I would much rather wait and release apple ARM and linux ARM together.

**Comment by wookayin** [comment]
@MordechaiHadad See https://github.com/actions/runner-images/issues/2187 -- it is possible to build a 'arm64' target on a Github macOS runner (x86_64).

```
stpes:
  with:
    toolchain: stable
    target: aarch64-apple-darwin
```

See dandavison/delta#1239, LiveSplit/livesplit-core#382, etc. for more live exapmles.

**Comment by MordechaiHadad** [comment]
@wookayin you are correct done, #75
