### ISSUE TITLE
The nightly build of Neovim downloaded with Bob 3.0.0 is using 99% CPU on UNIX

### ISSUE THREAD

**Issue by By1000101** [MordechaiHadad/bob#222]
When I use Bob 2.9.1 or other package managers to download, I don't have this issue

![Screenshot 2024-06-14 at 5 55 11 AM](https://github.com/MordechaiHadad/bob/assets/141002131/98a0bf7d-0baf-4bf2-987e-8cb41d246865)

**Comment by MordechaiHadad** [comment]
Can you run 
`nvim --&bob` (although I am not sure why this would matter)

**Comment by MordechaiHadad** [comment]
@By1000101 Should be fixed now, steps to check if it works on your end:

1. Get new bob binary, either by getting the artifact from the PR CI/building bob from source
2. Copy the binary into `bob/nvim-bin` and rename it to `nvim`
3. Run neovim and check the cpu usage.

**Comment by By1000101** [comment]
The PR fixed the issue of high CPU usage. Now, the CPU usage of Neovim is normal. Thank you!
