### ISSUE TITLE
Possible to install prerelease?

### ISSUE THREAD

**Issue by vzytoi** [MordechaiHadad/bob#23]
Hey, I just wanted to know if it is/will be possible to install prerelease version using `bob use prelease` ?
Thanks for your time, and btw really good plugin!

**Comment by MordechaiHadad** [comment]
> Hey, I just wanted to know if it is/will be possible to install prerelease version using `bob use prelease` ? Thanks for your time, and btw really good plugin!

I assume by prerelease you mean nightly
yes you can install nightly with `bob use nightly`

**Comment by vzytoi** [comment]
The problem was that when I typed `bob use nightly` and then `nvim -v` the output was 0.7.0 but you are completely right. Thank you!
