### ISSUE TITLE
list cmd is broken for 4.0.0 release

### ISSUE THREAD

**Issue by chenrui333** [MordechaiHadad/bob#230]
👋 looks like `bob list` is broken for 4.0.0 release

```
$ /opt/homebrew/Cellar/bob/4.0.0/bin/bob install v0.9.0
Downloaded version v0.9.0 to /Users/rui/.local/share/bob/v0.9.0.tar.gz
  [00:00:00] [██████████████████████████████████████] 11.78MiB/11.78MiB (27.25MiB/s, 0s)
Aug 19 07:11:41.479  INFO v0.9.0 has been successfully installed in /Users/rui/.local/share/bob

$ /opt/homebrew/Cellar/bob/4.0.0/bin/bob list
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
└───────────┴─────────────┘
```

relates to https://github.com/Homebrew/homebrew-core/pull/181650

**Comment by incoggnito** [comment]
Same for me, only nightly is listed currently.

**Comment by MordechaiHadad** [comment]
It seems like bob is not expanding the neovim archives for some dumb reason

**Comment by MordechaiHadad** [comment]
i found the issue give me a few minutes

**Comment by MordechaiHadad** [comment]
@chenrui333 @incoggnito can you test the artifacts from this https://github.com/MordechaiHadad/bob/actions/runs/10453155413

it should fix it

**Comment by chenrui333** [comment]
checking a5c0cda1e670d983599a4b0b561fcf430bfc1359 via https://github.com/Homebrew/homebrew-core/pull/181650

**Comment by incoggnito** [comment]
it works for me

**Comment by MordechaiHadad** [comment]
> it works for me

awesome, ill republish the release tomorrow

**Comment by MordechaiHadad** [comment]
@chenrui333 I assume it also fixed for you according to the output you gave me, so I am closing this issue. Feel free to reopen it if the issue persists.

**Comment by chenrui333** [comment]
yeah, I can just try the new release and open a new issue if I still see the problem.

**Comment by nurlord** [comment]
ubuntu 24.04 LTS, bob v4, bob-linux-x86-64, ran bob use stable it installed nvim
`➜  ~ nvim
Aug 21 15:49:45.857 ERROR Error: No such file or directory (os error 2)
➜  ~ bob list
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
└───────────┴─────────────┘
➜  ~ nvim
Aug 21 15:49:49.809 ERROR Error: No such file or directory (os error 2)
➜  ~ bob --version
bob-nvim 4.0.0`

**Comment by MordechaiHadad** [comment]
@nurlord can you show `~/.local/share/bob`?

**Comment by lackovic** [comment]
I am having the same issue on Ubuntu 24.04 LTS.

```sh
$ ./bob install stable
Aug 22 16:11:51.861  INFO Fetching latest version
Downloaded version v0.10.1 to /home/marco/.local/share/bob/v0.10.1.appimage
  [00:00:00] [██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 11.56MiB/11.56MiB (17.99MiB/s, 0s)
Aug 22 16:11:53.737  INFO v0.10.1 has been successfully installed in /home/marco/.local/share/bob

$ ./bob use stable
Aug 22 16:12:01.066  INFO Fetching latest version
Aug 22 16:12:01.312  INFO v0.10.1 is already installed and used!

$ nvim
Aug 22 16:12:04.204 ERROR Error: No such file or directory (os error 2)
``` 

> ill republish the release tomorrow

Did you republish with the same version?

> can you show ~/.local/share/bob?

```sh
$ dir ~/.local/share/bob
total 12M
drwxr-xr-x 2 marco marco 4.0K Aug 21 17:37 nvim-bin/
-rw-r--r-- 1 marco marco    7 Aug 21 17:37 used
-rw-r--r-- 1 marco marco  12M Aug 22 13:25 v0.10.1.appimage

$ dir ~/.config/nvim/
ls: cannot access '/home/marco/.config/nvim/': No such file or directory
```

**Comment by MordechaiHadad** [comment]
> I am having the same issue on Ubuntu 24.04 LTS. Also `nvim` doesn't work.
> 
> ```shell
> $ ./bob install stable
> Aug 22 16:11:51.861  INFO Fetching latest version
> Downloaded version v0.10.1 to /home/marco/.local/share/bob/v0.10.1.appimage
>   [00:00:00] [██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 11.56MiB/11.56MiB (17.99MiB/s, 0s)
> Aug 22 16:11:53.737  INFO v0.10.1 has been successfully installed in /home/marco/.local/share/bob
> 
> $ ./bob use stable
> Aug 22 16:12:01.066  INFO Fetching latest version
> Aug 22 16:12:01.312  INFO v0.10.1 is already installed and used!
> 
> $ nvim
> Aug 22 16:12:04.204 ERROR Error: No such file or directory (os error 2)
> ```
> 
> > ill republish the release tomorrow
> 
> Did you republish with the same version?
> 
> > can you show ~/.local/share/bob?
> 
> ```shell
> $ dir ~/.local/share/bob
> total 12M
> drwxr-xr-x 2 marco marco 4.0K Aug 21 17:37 nvim-bin/
> -rw-r--r-- 1 marco marco    7 Aug 21 17:37 used
> -rw-r--r-- 1 marco marco  12M Aug 22 13:25 v0.10.1.appimage
> 
> $ dir ~/.config/nvim/
> ls: cannot access '/home/marco/.config/nvim/': No such file or directory
> ```
> 
> As a **workaround** I am using the earlier [version 3.0.1](https://github.com/MordechaiHadad/bob/releases/tag/v3.0.1), that works fine.

I did republish with the same version, and yes it does seem like you are using the bad release I released.

**Comment by MordechaiHadad** [comment]
Also out of curiosity how do u manage to install bob on ubuntu? Afaik the only distro that bob is in the official repos is Arch

**Comment by NicolasGB** [comment]
Hey since using v4 i'm having problems with bob. It doesn't set stable versions only nighlty ones. Also when updates are available, it doesn't manage to update saying "file not found" as shown  in the following image (bun is an alias for `bob update nightly`).

The workaround is erasing and installing nightly.

I'm on arch, using v4.0.0-2.

![bob update not working](https://github.com/user-attachments/assets/66d83ffd-5fbe-49b2-b496-230c5e7ee807)

**Comment by MordechaiHadad** [comment]
> Hey since using v4 i'm having problems with bob. It doesn't set stable versions only nighlty ones. Also when updates are available, it doesn't manage to update saying "file not found" as shown in the following image (bun is an alias for `bob update nightly`).
> 
> The workaround is erasing and installing nightly.
> 
> I'm on arch, using v4.0.0-2.
> 
> ![bob update not working](https://private-user-images.githubusercontent.com/17547539/360828836-66d83ffd-5fbe-49b2-b496-230c5e7ee807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTg2MDksIm5iZiI6MTcyNDM5ODMwOSwicGF0aCI6Ii8xNzU0NzUzOS8zNjA4Mjg4MzYtNjZkODNmZmQtNWZiZS00OWIyLWI0OTYtMjMwYzVlN2VlODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNWI3ODU0YjJjY2ExNGEzMGQ0MzBjMGJiNDY0MGUwNzFkN2EzODkzYzI4ZDAwOWViYmM2OWNjODYxYjViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZKMq6jbFchMz8oufWTVp1yXJMfUwzLKMOnwFM863YO4)

Hmm interesting seems like updating nightly via `update` instead of use/install breaks.
