### ISSUE TITLE
The macos x86 version prompts for a bad CPU type.

### ISSUE THREAD

**Issue by 0x7a7a** [MordechaiHadad/bob#235]
I checked the `.github`, and found that macos' x86 platform compilation uses `macos-lastest`.
Currently `macos-latest` defaults to the arm64, not x86, can you confirm?

Relevant information:
https://github.com/actions/runner-images#available-images
https://github.com/actions/runner-images/issues/9741
https://www.reddit.com/r/github/comments/1cjiat4/is_github_actions_macoslatest_now_only_armbased/

**Comment by MordechaiHadad** [comment]
> I checked the `.github`, and found that macos' x86 platform compilation uses `macos-lastest`. Currently `macos-latest` defaults to the arm64, not x86, can you confirm?
> 
> Relevant information: [actions/runner-images#available-images](https://github.com/actions/runner-images#available-images) [actions/runner-images#9741](https://github.com/actions/runner-images/issues/9741) [reddit.com/r/github/comments/1cjiat4/is_github_actions_macoslatest_now_only_armbased](https://www.reddit.com/r/github/comments/1cjiat4/is_github_actions_macoslatest_now_only_armbased/)

You are right thank you for letting me know!

**Comment by MordechaiHadad** [comment]
There is some odd thing with the x86 runner I can't use it lmao.

**Comment by 0x7a7a** [comment]
Will there be any problems if change the x86 compilation platform to macos-13?

**Comment by MordechaiHadad** [comment]
I am unsure I'll have to test it

**Comment by 0x7a7a** [comment]
Thank you for your work. 
If that doesn't fix it, I suggest removing the x86 version from the release to prevent misunderstandings.

**Comment by MordechaiHadad** [comment]
> Thank you for your work. 
> If that doesn't fix it, I suggest removing the x86 version from the release to prevent misunderstandings.

Yes, I will remove it for now until I get it sorted.

**Comment by MordechaiHadad** [comment]
It seems like `macos-13-large` this is just ridiculous

**Comment by MordechaiHadad** [comment]
@0x7a7a can you confirm the x86 build works for you?

https://github.com/MordechaiHadad/bob/actions/runs/10791225725/attempts/1

**Comment by 0x7a7a** [comment]
> @0x7a7a can you confirm the x86 build works for you?
> 
> [MordechaiHadad/bob/actions/runs/10791225725/attempts/1](https://github.com/MordechaiHadad/bob/actions/runs/10791225725/attempts/1)

Sure, I tested it and it works.
