### ISSUE TITLE
[Feature] Add a hint when "Text file busy (os error 26)" error occurs.

### ISSUE THREAD

**Issue by piotr-calus** [MordechaiHadad/bob#236]
When trying to change nvim version (_bob use_) user may get "**Text file busy (os error 26)**".
```
$ bob list
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
│  v0.10.1  │  Installed  │
│  v0.9.5   │  Used       │
└───────────┴─────────────┘

$ bob use stable
INFO Fetching latest version
INFO Updating neovim proxy
ERROR Error: Text file busy (os error 26)
```

The reason is that the binary file is in use by some running process.

**Quick solution** (for the user)
The most elegant solution is to close the processes that are locking the binary file. User can find which ones in many ways, eg. using fuser ([man fuser](https://linux.die.net/man/1/fuser)):
```
fuser -v $(which nvim)
                     USER        PID ACCESS COMMAND
/home/pcalus/.local/share/bob/nvim-bin/nvim:
                     <user>    <pid1> ...e. nvim
                     <user>    <pid2> ...e. nvim
```
...or ps+lsof ([man ps](https://linux.die.net/man/1/ps), [man lsof](https://linux.die.net/man/8/lsof)).
```
ps -o pid,command $(lsof -t $(which nvim))
    PID COMMAND
<pid1> <path_to_nvim> -N --embed --cmd source ~/.vscode-oss/extensions/asvetliakov.vscode-neovim-1.18.9-universal/runtime/vscode-neovim.vim
<pid2> <path_to_nvim> -N --embed --cmd source ~/.vscode-oss/extensions/asvetliakov.vscode-neovim-1.18.9-universal/runtime/vscode-neovim.vim
```
In the above case the culprit is VSCodium with the neovim plugin, which is expected.

Eventually We can:
* documentation: add a note ([README.md](https://github.com/MordechaiHadad/bob/blob/master/README.md)?)
* runtime, when an error occurs...
  * print a hint to the user to close processes blocking nvim binary
  * print information about these processes (to make it easier to close them).

**Comment by MordechaiHadad** [comment]
I will add the runtime clarification error but without the specific process since on windows u have to have admin privileges (maybe ill add for unix we will see)

**Comment by MordechaiHadad** [comment]
@piotr-calus can you confirm that the PR fixes this issue?

**Comment by piotr-calus** [comment]
> @piotr-calus can you confirm that the PR fixes this issue?

It seems to be ok.
Good job, thanks!

```
$ fuser -v $(which nvim)
                     USER        PID ACCESS COMMAND
/home/pcalus/.local/share/bob/nvim-bin/nvim:
                     pcalus    920651 ...e. nvim

$ bob --version
bob-nvim 4.0.1

$ bob use nightly
Sep 10 22:11:27.791  INFO Updating neovim proxy
Sep 10 22:11:27.792 ERROR Error: Text file busy (os error 26)

$ git branch --show-current
notify-user-file-busy

$ cargo run use nightly
[...]
     Running `target/debug/bob use nightly
Sep 10 22:11:45.264  INFO Looking for nightly updates
Sep 10 22:11:45.266  INFO You can now use nightly!
```

**Comment by MordechaiHadad** [comment]
> > @piotr-calus can you confirm that the PR fixes this issue?
> 
> It seems to be ok. Good job, thanks!
> 
> ```
> $ fuser -v $(which nvim)
>                      USER        PID ACCESS COMMAND
> /home/pcalus/.local/share/bob/nvim-bin/nvim:
>                      pcalus    920651 ...e. nvim
> 
> $ bob --version
> bob-nvim 4.0.1
> 
> $ bob use nightly
> Sep 10 22:11:27.791  INFO Updating neovim proxy
> Sep 10 22:11:27.792 ERROR Error: Text file busy (os error 26)
> 
> $ git branch --show-current
> notify-user-file-busy
> 
> $ cargo run use nightly
> [...]
>      Running `target/debug/bob use nightly
> Sep 10 22:11:45.264  INFO Looking for nightly updates
> Sep 10 22:11:45.266  INFO You can now use nightly!
> ```

Hmm odd, the error should be different.

**Comment by MordechaiHadad** [comment]
ah I can see why, the new version is actually 4.0.2

**Comment by piotr-calus** [comment]
> ah I can see why, the new version is actually 4.0.2. so you probably didn't switch correctly to the new branch.

Oh, wait. I think I didn't express myself clearly.

The problem occurs in the (tagged) version 4.0.1:
> ```
> $ bob --version
> bob-nvim 4.0.1
> 
> $ bob use nightly
> Sep 10 22:11:27.791  INFO Updating neovim proxy
> Sep 10 22:11:27.792 ERROR Error: Text file busy (os error 26)
> ```

and in the *notify-user-file-busy* branch (PR #238) it works, no more errors 👍🏻 
> ```
> $ git branch --show-current
> notify-user-file-busy
> 
> $ cargo run use nightly
> [...]
>      Running `target/debug/bob use nightly
> Sep 10 22:11:45.264  INFO Looking for nightly updates
> Sep 10 22:11:45.266  INFO You can now use nightly!
> ```
I added both console outputs as "test log". Sorry if I misled you with that. I should have made that clear from the start.

**Comment by MordechaiHadad** [comment]
🤔

**Comment by piotr-calus** [comment]
Retesting...
Trying to reproduce the failure again I get the error "**Error: The file is busy**".
```
$ cargo run use stable
Sep 11 11:37:48.271  INFO Fetching latest version
Sep 11 11:37:48.852  INFO Updating neovim proxy
Sep 11 12:05:47.862 ERROR Error: The file /home/pcalus/workspace/bob/target/debug/bob is busy. Please make sure to close any processes using it.
```
I did not look at the code. Is it the bob file that is supposed to be copied?
> ~/workspace/bob/target/debug/bob -> ~/.local/share/bob/nvim-bin/nvim
🤔

Additional info:
```
$ git log --oneline -n 1
88a7985 (HEAD, origin/notify-user-file-busy) lol

$ cargo run -- --version
warning: unused manifest key: bin.0.plugin
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/bob --version`
bob-nvim 4.0.2

$ ls -1 /home/pcalus/.local/share/bob/
nightly
nightly-648d642
nvim-bin
used
v0.10.1

$ cargo run list
warning: unused manifest key: bin.0.plugin
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/bob list`
┌────────────────────┬─────────────┐
│  Version           │  Status     │
├────────────────────┼─────────────┤
│  v0.10.1           │  Installed  │
│  nightly-648d642   │  Installed  │
│  nightly           │  Used       │
└────────────────────┴─────────────┘
```

**Comment by MordechaiHadad** [comment]
> Retesting... Trying to reproduce the failure again I get the error "**Error: The file is busy**".
> 
> ```
> $ cargo run use stable
> Sep 11 11:37:48.271  INFO Fetching latest version
> Sep 11 11:37:48.852  INFO Updating neovim proxy
> Sep 11 12:05:47.862 ERROR Error: The file /home/pcalus/workspace/bob/target/debug/bob is busy. Please make sure to close any processes using it.
> ```
> 
> I did not look at the code. Is it the bob file that is supposed to be copied?
> 
> > ~/workspace/bob/target/debug/bob -> ~/.local/share/bob/nvim-bin/nvim
> > 🤔
> 
> Additional info:
> 
> ```
> $ git log --oneline -n 1
> 88a7985 (HEAD, origin/notify-user-file-busy) lol
> 
> $ cargo run -- --version
> warning: unused manifest key: bin.0.plugin
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
>      Running `target/debug/bob --version`
> bob-nvim 4.0.2
> 
> $ ls -1 /home/pcalus/.local/share/bob/
> nightly
> nightly-648d642
> nvim-bin
> used
> v0.10.1
> 
> $ cargo run list
> warning: unused manifest key: bin.0.plugin
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
>      Running `target/debug/bob list`
> ┌────────────────────┬─────────────┐
> │  Version           │  Status     │
> ├────────────────────┼─────────────┤
> │  v0.10.1           │  Installed  │
> │  nightly-648d642   │  Installed  │
> │  nightly           │  Used       │
> └────────────────────┴─────────────┘
> ```

Okay looking at the first output yes it works as intented, awesome.
