### ISSUE TITLE
[Feature request]: Install older nightly versions

### ISSUE THREAD

**Issue by lmburns** [MordechaiHadad/bob#29]
The reason I am requesting this is because the latest nightly version has caused an error with an autocommand that I have that restores the cursor position. I would like to continue using the autocommand, but find it somewhat difficult to go to a previous nightly version. If I install the stable release then some of the `api` calls I have in my configuration won't work.

Would it be possible to specify a date for the nightly version release? If something like this were to happen again, I could just do `bob install nightly <yesterday's date>`. 

Another option would be to use the commit hash like `bob install nightly 60604d6`.  Or the nightly could be dropped and just a commit hash could be given.

Editing to say that I am unsure exactly how to see previous nightly releases. I can't seem to figure out how to find older versions that have been released with the tag `nightly`. I still think that the commit hash would work as an option to rollback the current nightly version.

**Comment by MordechaiHadad** [comment]
Hello! thanks for opening the issue.
I too have no idea how to get previous nightly builds, I was suggested before being able to build neovim from a specific commit has, would that of interest to you?

**Comment by lmburns** [comment]
Yes, having a commit hash as an argument would be good

**Comment by MordechaiHadad** [comment]
@lmburns do you feel like testing hash-support branch? so far tests seem to be working correctly.

**Comment by lmburns** [comment]
Yeah, I've actually been using that branch since last month and everything seems to work just fine. I haven't ran into any issues. I just pulled the repo and reinstalled it to check whether or not installing with a hash works and it seems to be fine as well.

**Comment by MordechaiHadad** [comment]
glad to know! it seems only macos support is taking the piss now

**Comment by lmburns** [comment]
How is macOS having problems? I am downloading it on my mac now. Does it have something to do with permission issues?

**Comment by MordechaiHadad** [comment]
@lmburns no permissions issues but it seems like it has some issues when building, 
you need to make sure you have those deps https://github.com/neovim/neovim/wiki/Building-Neovim#macos--homebrew

**Comment by MordechaiHadad** [comment]
I plan on merging the PR tomorrow!
