### ISSUE TITLE
failed to install when trying to use bob as a standalone

### ISSUE THREAD

**Issue by uneconomicalfairy14** [MordechaiHadad/bob#31]
i installed bob by downloading the binary from releases section
extracting it to ~/.bob/bin
exporting the path in zshrc
and changing it to a executable by chmod +x bob

yet
on calling this cmd
bob use stable
the following error is returned
```
bob: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
i tried installing openssl, but it is manually installed for me

i m using ubuntu 22.04(LTS)

i dont want to install rust for bob therefore if someone could provide a solution to install dependencies without making much changes to my system files..

**Comment by MordechaiHadad** [comment]
@uneconomicalfairy14 hey thanks for opening the issue and sorry for the long time it took me to respond...

I will look into this tomorrow, but you don't really need to have rust installed in order to run bob(unless I am mistaken)
and the error is pretty weird.
Thank you for reporting!
Could you also provide the version of openssl you are using?

**Comment by uneconomicalfairy14** [comment]
> @uneconomicalfairy14 hey thanks for opening the issue and sorry for the long time it took me to respond...
> 
> I will look into this tomorrow, but you don't really need to have rust installed in order to run bob(unless I am mistaken) and the error is pretty weird. Thank you for reporting! Could you also provide the version of openssl you are using?


version of openssl
openssl 3.0.2-0ubuntu1.6(main)

**Comment by MordechaiHadad** [comment]
@uneconomicalfairy14 sorry it took me some time to get to fix this issue, I have been fallen ill and was busy with some stuff.
I am gonna push a new release, you would want to use the rustls version, i would also like some feedback when u get to download it, if you would have any of course.
