### ISSUE TITLE
Error installing nvim

### ISSUE THREAD

**Issue by MrEmii** [MordechaiHadad/bob#36]
When I run ```bob install v0.7.2``` it throws this error

![image](https://user-images.githubusercontent.com/32276305/183528313-54c39731-b008-49a0-8327-e1e0e882d986.png)

**Comment by MordechaiHadad** [comment]
@MrEmii can you try opening the specified URL in your browser?

**Comment by MrEmii** [comment]
Of course, it downloads the file shown in the image.
![image](https://user-images.githubusercontent.com/32276305/183628581-5eadd9df-8ac8-4a68-ac21-c36c3468ece4.png)

**Comment by MordechaiHadad** [comment]
Can you provide system info so I can try to reproduce this error?

**Comment by MrEmii** [comment]
system information:
![image](https://user-images.githubusercontent.com/32276305/183634867-692cfc83-8084-472b-960b-deb7df6531b4.png)

Cargo version: cargo 1.62.0 

I don't know which version of Bob I have, but it is the one installed with the command
```
cargo install --git https://github.com/MordechaiHadad/bob.git
```

**Comment by MordechaiHadad** [comment]
@MrEmii I have been able to reproduce the issue thankfully, currently you can use `bob-linux-rustls` on releases and it will work just fine, the main difference is just not relying on openssl really.
I will keep looking into this issue and see what I can do to fix this.

**Comment by BinxDot** [comment]
Hi, I'm having the same issue as @MrEmii on Windows 10.

**Comment by MordechaiHadad** [comment]
![image](https://user-images.githubusercontent.com/33547558/183701086-1256fa3b-16a3-4063-9e2a-9b9823e5d1f5.png)

**Comment by MrEmii** [comment]
![image](https://user-images.githubusercontent.com/32276305/183702261-fa8b718a-3d84-472c-b842-ddc45d83b0e4.png)

**Comment by iChard** [comment]
Hi, I'm having the same issue as @MrEmii  on macos 12.5

**Comment by MordechaiHadad** [comment]
@iChard do you know which version of bob? if the latest then I think I know what causes this issue.

**Comment by iChard** [comment]
@MordechaiHadad  yes,the lastest~.i just installed it minutes ago

**Comment by MordechaiHadad** [comment]
@iChard for now download one release before, thankfully you guys were able to notify me of this right away.
I do not know how this released passed my tests.

**Comment by MordechaiHadad** [comment]
I have made the dumbest mistake in the history of dumb programming mistakes, and it will stay on the internet forever 🤦‍♂️

**Comment by MordechaiHadad** [comment]
@MrEmii @iChard @BinxDot I have fixed this issue, I would also suggest testing and if there's any feedback write it here, I have tested on windows, Arch linux and basic pop-os installation.

@MrEmii for you specifically and for ubuntu/debian(?) based distros use the rustls version as for some reason their openSSL version clashes with the version bob expects, I will also write that on the release that i will open today.

**Comment by MrEmii** [comment]
The rustl version continues to give the same error.
![image](https://user-images.githubusercontent.com/32276305/183941348-758872f4-72e9-4ecc-879d-3489a40c84f7.png)
also, the new version with charge works perfectly, thank you.

**Comment by MordechaiHadad** [comment]
@MrEmii what exactly you mean by charge?

**Comment by MordechaiHadad** [comment]
@MrEmii its weird that rustls version doesn't work for you but the openssl does, I have tested it 2 times now on a plain pop-os docker image with no changes, only made a bob user, and downloaded neofetch(after trying bob) and it works just fine
![image](https://user-images.githubusercontent.com/33547558/184111403-a0fa3ff3-3e11-41ad-809c-699995275825.png)
![image](https://user-images.githubusercontent.com/33547558/184112227-91cb1555-d98d-44b0-bf89-1547a4989f1c.png)
