### ISSUE TITLE
Cannot use with multiple users

### ISSUE THREAD

**Issue by jonwest** [MordechaiHadad/bob#41]
It doesn't seem to be possible to install this properly for multiple users.

In an Ubuntu 20.04 installation, if I first bring in the binary from the releases page as the root user into `/usr/bin`, and run `bob install stable` and then `bob use stable`, if I try to use the binary as another user, I will get `ERROR Error: Couldn't create downloads directory`.

If I try to uninstall `bob` using `bob erase`, and set ownership of the `bob` binary to the non-root user, and then try to subsequently run `bob install stable`, I will still get `ERROR Error: Couldn't create downloads directory`.  If I run `bob` using `sudo`, I _can_ install the package, but it still installs to `/root/.local/share/neovim/bin`, so it seems there is still some config left over that isn't cleaned up with `erase`.

**Comment by MordechaiHadad** [comment]
Lol that was a bit of a hard error to read, but I think I understand what you describing...
I will boot up an ubuntu docker machine and test it out today.

**Comment by MordechaiHadad** [comment]
@jonwest Okay I found what caused this error, is because it is looking for directory `.local/share` if you don't have those directories in your user's home dir it won't install it correctly,
I will try to give a better error message regarding this error.

Also in the last part what exactly do you mean try to uninstall bob with `bob erase`? erase is only to erase downloaded versions and remove the used version.

**Comment by MordechaiHadad** [comment]
@jonwest any update?

**Comment by MichaelZhang-Navex** [comment]
> @jonwest Okay I found what caused this error, is because it is looking for directory `.local/share` if you don't have those directories in your user's home dir it won't install it correctly, I will try to give a better error message regarding this error.
> 
> Also in the last part what exactly do you mean try to uninstall bob with `bob erase`? erase is only to erase downloaded versions and remove the used version.

Got same issue here. and solved by creating ~/.local/share/ folder.

**Comment by MordechaiHadad** [comment]
@MichaelZhang-Navex yeah exactly what I thought... hmm maybe I'll just make it make a directory recursively like `mkdir -p` or something

**Comment by MordechaiHadad** [comment]
I guess I'll close this issue for lack of activity and the fact that this is easily resolved by @MichaelZhang-Navex
