### ISSUE TITLE
ERROR: failed to compile

### ISSUE THREAD

**Issue by zubrailx** [MordechaiHadad/bob#44]
### Description

Error while compiling bob.
```
   Compiling bob v1.1.2 (/home/nikit/.cargo/git/checkouts/bob-f97b36b3fbc90c07/d4c00fc)
error[E0433]: failed to resolve: could not find `private` in `anyhow`
   --> src/modules/install_handler.rs:112:49
    |
112 |                     let chunk = item.or(anyhow::private::Err(anyhow::Error::msg("hello")))?;
    |                                                 ^^^^^^^ could not find `private` in `anyhow`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `bob` due to previous error
error: failed to compile `bob v1.1.2 (https://github.com/Mordech
```

### Version

```markdown
openssl 1.1.1q
rustc 1.62.1 (e092d0b6b 2022-07-16)
```

### Operating system and version

Gentoo Base System release 2.8 x86_64
Kernel: 5.15.59-gentoo

### Steps to reproduce

1. Run: `cargo install --git https://github.com/MordechaiHadad/bob.git -F bob/openssl`

### Expected behavior

Compilation completed successfully.

### Actual behavior

Got an error above.

**Comment by MordechaiHadad** [comment]
I have seen this error a couple of times I think already which is weird.
Thanks for opening the issue I will try to address it in time!

**Comment by ngilles** [comment]
I got this error as well when building when from `cargo install ...` but building from checkout out source works fine?

**Comment by MordechaiHadad** [comment]
@ngilles oh really? that's odd...
maybe it's some bug with cargo idk

**Comment by MordechaiHadad** [comment]
> I got this error as well when building when from `cargo install ...` but building from checkout out source works fine?

I actually got to test this today, and you are correct.
Weird issue
