### ISSUE TITLE
bob install nightly|stable fails

### ISSUE THREAD

**Issue by Raekh** [MordechaiHadad/bob#49]
I'm on MacOS and I can't install nvim nightly nor stable. When it fails, bob stops working (complaining about bob.json) and I have to run it again so that responds again.

Using bob install with version number works fine tho.

I'm using the one from the Releases page, as it was impossible to compile it nor install it with cargo.
```
froura@Devourer 
--------------- 
OS: macOS 12.5 21G72 x86_64 
Host: MacBookPro16,1 
Kernel: 21.6.0 
Uptime: 59 mins 
Packages: 59 (brew) 
Shell: zsh 5.8.1 
Resolution: 1792x1120 
DE: Aqua 
WM: Amethyst 
Terminal: tmux 
CPU: Intel i7-9750H (12) @ 2.60GHz 
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M 
Memory: 13865MiB / 32768MiB 
```
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/24220353/189542365-2905acc2-8bd3-4230-9533-3bd66cba9f42.png">

**Comment by max397574** [comment]
I get exactly the same

**Comment by MordechaiHadad** [comment]
@max397574 @Raekh could you try downloading the latest action build from this PR: https://github.com/MordechaiHadad/bob/pull/40
It seems like it's the same issue in https://github.com/MordechaiHadad/bob/issues/32 which i have created #40 which seems to resolved it but the previous tester stopped testing the PR

**Comment by MordechaiHadad** [comment]
Also regarding installing bob with `cargo install` it is seems like it's bugged for everyone(me included) but I don't think its an issue with bob rather with either cargo or anyhow, which i currently don't know for sure

**Comment by MordechaiHadad** [comment]
this issue is the same as #32 so i'll close this one

**Comment by max397574** [comment]
using the build from the pr fixed the issue for me
