### ISSUE TITLE
cargo install failed

### ISSUE THREAD

**Issue by rachmadaniHaryono** [MordechaiHadad/bob#51]
first using cargo 1.58.0 i got following error

```console
> cargo install --git https://github.com/MordechaiHadad/bob.git -F bob/rustls
error: Found argument '-F' which wasn't expected, or isn't valid in this context

USAGE:
    cargo install --git <URL>
```

so i update my to cargo 1.61.0 

```console
> cargo install --git https://github.com/MordechaiHadad/bob.git -F bob/rustls
error: Found argument '-F' which wasn't expected, or isn't valid in this context

        If you tried to supply `-F` as a value rather than a flag, use `-- -F`

USAGE:
    cargo install [OPTIONS] [--] [crate]...
```

so install with only the url and it work `cargo install --git https://github.com/MordechaiHadad/bob.git`

openssl version

```console
> openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

**Comment by bryant-the-coder** [comment]
in the readme, it isnt recommended to use `cargo` to install bob. download it from the release.

**Comment by MordechaiHadad** [comment]
@rachmadaniHaryono can you try replacing `-F` with `--features`?

**Comment by rachmadaniHaryono** [comment]
that work

looking at https://doc.rust-lang.org/cargo/commands/cargo-install.html#feature-selection `-F` is valid options

but https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options and `cargo install --help` only list `--features`

i will create pr for this
