### ISSUE TITLE
issue : bob use xxx

### ISSUE THREAD

**Issue by akirco** [MordechaiHadad/bob#53]
when i use custom configuration, the following error:
```powershell
➜ bob use stable
Oct 13 14:01:26.334 ERROR Error: 另一个程序正在使用此文件，进程无法访问。 (os error 32)
```
i'm thinking if `install,uninstall,use` will read the config file，i think it should be putting the config file with the execute file

OS: Windows 11

**Comment by MordechaiHadad** [comment]
@akirco can you translate this text to english? also can you show the custom config perhaps?

**Comment by akirco** [comment]
that means `another program is using this file adnd the process can not be accessed  (os error 32)`. but there is no problem,now.

**Comment by MordechaiHadad** [comment]
oh I see
