### ISSUE TITLE
Idea to solucionate MacBook M1 Pro install problem

### ISSUE THREAD

**Issue by cscovino** [MordechaiHadad/bob#54]
I have the same issues as #32 

I don't know rust, but I think you could add an if statement to check the target architecture so you can differentiate mac intel from M1, then the symlink is created correctly and also set correct permissions to the files.

So I think this could be a solution using [target_arch](https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch)
```
use_handler.rs
...
        } else {
            use std::os::unix::fs::symlink;
            let folder_name = if cfg!(target_os = "macos") {
                if cfg!(target_arch = "arm") {
                    "nvim-macos"
                } else {
                    "nvim-osx64"
                }
            } else {
                "nvim-linux64"
            };
            if let Err(error) = symlink(format!("{base_path}/{folder_name}"), &installation_dir) {
                return Err(anyhow!(error))
            }
        }
....
```

```
expand_archive.rs
...
    pb.finish_with_message(format!(
        "Finished expanding to {}/{}",
        downloaded_file.path, downloaded_file.file_name
    ));
    let platform = if cfg!(target_os = "macos") {
        if cfg!(target_arch = "arm") {
            "nvim-macos"
        } else {
            "nvim-osx64"
        }
    } else {
        "nvim-linux64"
    };
    let file = &format!("{}/{platform}/bin/nvim", downloaded_file.file_name);
    let mut perms = fs::metadata(file)?.permissions();
    perms.set_mode(0o111);
    fs::set_permissions(file, perms)?;
    Ok(())
...
```

sorry if there are syntax errors 😅. Also, I can open a PR if you guide me on how to test it.

**Comment by cscovino** [comment]
I have the same issues as #32

**Comment by MordechaiHadad** [comment]
I have no idea how this is going to change anything... neovim only provides one binary for macos `nvim-macos` there isn't `nvim-osx64` 
Are you getting this issue on an 86x macos? also which version of bob are you using?
and unfortunately M1 isn't fully supported because I have no way to compile it to M1 native so if something works fine on 86x machine but not on M1 I don't know a proper way to fix it...

**Comment by cscovino** [comment]
> neovim only provides one binary for macos `nvim-macos` there isn't `nvim-osx64`

Ok, Do you not have to change that in the code?
I am getting the issue on M1, nvim is installed in `nvim-macos` folder but bob creates the symlink for `nvim-osx64` folder and then when it tries to change the file permissions also fails because it is in another folder.

I installed bob a few days ago I don't know how to know the version, is there a command to know the version?

**Comment by MordechaiHadad** [comment]
Hmmmmm interesting... newer versions of neovim `0.8.0` and up changed the directory contained inside the macos release from nvim-osx64 to nvim-macos
I will have to push a hot fix

**Comment by MordechaiHadad** [comment]
@cscovino I will need you to test the bob releases from the attached PR so I can know if the changes fixed the issue.

**Comment by cscovino** [comment]
@MordechaiHadad It is fixed, thanks!

**Comment by MordechaiHadad** [comment]
I am glad to hear
