### ISSUE TITLE
Not able to install the `hash-support` branch with `cargo install`

### ISSUE THREAD

**Issue by folke** [MordechaiHadad/bob#56]
Hi!

First of all, I love your project! It makes it so much easier to test my plugins on different versions.

I would love to try out the new branch, but I get an error when building:

![image](https://user-images.githubusercontent.com/292349/196108434-56f65213-9620-4c55-b15e-cabc3cdf0189.png)

**Comment by MordechaiHadad** [comment]
😅wanted to avoid having to keep `hash-support` branch updated with `master` because merge conflicts, guess I'll have to to it.
I will attend to it tomorrow and update you.

**Comment by MordechaiHadad** [comment]
@folke can you try running the same command now?

**Comment by folke** [comment]
Same problem unfortunately:
![image](https://user-images.githubusercontent.com/292349/196393765-5521dc53-2582-4fd9-901e-68843c9fed26.png)

**Comment by MordechaiHadad** [comment]
@folke weird that should have changed due to #50 give me a sec ill edit it rq

**Comment by MordechaiHadad** [comment]
@folke try now i have pushed a new commit

**Comment by folke** [comment]
Works now. Thanks!

Will try the new version stuff now :)
