### ISSUE TITLE
Error: Couldn't create downloads directory

### ISSUE THREAD

**Issue by kumkee** [MordechaiHadad/bob#63]
I follow the build instruction on an aarch64 machine. Building itself was successful, but when running `bob list` I got
```
ERROR Error: Couldn't create downloads directory
```

**Comment by MordechaiHadad** [comment]
@kumkee What OS are you using on ur aarch64 machine?

**Comment by kumkee** [comment]
> @kumkee What OS are you using on ur aarch64 machine?

Debian on Chromebook.

**Comment by MordechaiHadad** [comment]
@kumkee could you manually run `mkdir ~/.local/share/bob` and see if it still works?

**Comment by kumkee** [comment]
> @kumkee could you manually run `mkdir ~/.local/share/bob` and see if it still works?

Sure, but I won't be able to do that until tomorrow. Will let you know the result. Thanks for your prompt response.

**Comment by MordechaiHadad** [comment]
@kumkee no problem! intuitively I think the problem might be caused because you don't have `/.local/share` in ur home dir but that is just a guess.

**Comment by kumkee** [comment]
I can install neovim after manually creating the folder.
However, it got
```
zsh: permission denied: .local/share/neovim/bin/nvim
```
Does it have anything to do with the fact that I am using an ARM architecture?

**Comment by kumkee** [comment]
> What was the command that you ran that caused this permission error?

nvim

**Comment by MordechaiHadad** [comment]
@kumkee weird... can you show me your PATH?

**Comment by MordechaiHadad** [comment]
can you run `bob ls`?
also what happens if u run `sudo nvim`?

**Comment by kumkee** [comment]
> can you run `bob ls`? 

```
$ bob list
Version | Status
--------+----------
v0.8.0  | Used
```

> also what happens if u run `sudo nvim`?

```
$ sudo .local/share/neovim/bin/nvim 
.local/share/neovim/bin/nvim: 11: Syntax error: "(" unexpected
```

**Comment by MordechaiHadad** [comment]
@kumkee what if u change in path from $HOME to the full path?(I doubt if it would matter but I have no idea what is causing this weird error)

**Comment by kumkee** [comment]
Just found out `$HOME/.local/share/neovim/bin/nvim` is a symlink to `$HOME/.local/share/bob/v0.8.0/nvim-linux64/bin/nvim`.
The name of the latter suggests it is for x86_64 instead of arm64.

**Comment by MordechaiHadad** [comment]
Yeah that's true but neovim doesn't really publish any arm64 binaries as far as I know

**Comment by kumkee** [comment]
That is the answer then.

Does bob provide an option to build neovim from source?

**Comment by MordechaiHadad** [comment]
@kumkee yeah for sure with the latest release!
But i am unsure if it will work on arm... but you can try.

**Comment by MordechaiHadad** [comment]
@kumkee any luck with building?

**Comment by kumkee** [comment]
Haven't got a chance to try yet.
What is the bob installation flag for building neovim from source? I don't see that in your readme.

**Comment by MordechaiHadad** [comment]
`bob install <commit-hash>`

**Comment by kumkee** [comment]
```
No update step for 'unibilium'
[ 49%] No patch step for 'unibilium'
[ 50%] No configure step for 'unibilium'
[ 51%] Performing build step for 'unibilium'
make[4]: Entering directory '/home/[username]/.local/share/bob/neovim-git/.deps/build/src/unibilium'
make[4]: libtool: No such file or directory
make[4]: *** [Makefile:69: unibilium.lo] Error 127
```

I have confirmed that I have `libtool` and met [building requirement](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites)

**Comment by MordechaiHadad** [comment]
@kumkee hmmm I see,
listen what you can try...

git clone neovim repo and run this command `make CMAKE_BUILD_TYPE=RelWithDebInfo`
its more or less the commands bob uses, but I just want to see if u get the same errors if u do them manually...
And I don't really see any arm specific docs in their wiki.

**Comment by MordechaiHadad** [comment]
@kumkee I suggest we move this to a discussion and close this issue.

**Comment by kumkee** [comment]
Makes sense.
It unrelated to the title now
