### ISSUE TITLE
Why isn't this crate uploaded to `crates.io`?

### ISSUE THREAD

**Issue by ok-nick** [MordechaiHadad/bob#64]
I understand the conflict with the existing `bob` crate, but why not at least upload it under a different name? I know I could technically install it using the `--git` and `--tag` arguments to `cargo`, but that's pretty unorthodox (and tedious). Is there a specific reason it was done this way?

**Comment by MordechaiHadad** [comment]
@ok-nick the only reason I didn't upload it to crates.io is because I haven't got to uploading it.
I will upload it eventually.

**Comment by MordechaiHadad** [comment]
@ok-nick what do you think of `bob-nvim` as the name for the crates.io package?

**Comment by MordechaiHadad** [comment]
🤔 if i change the name for the crates.io it would be `bob-nvim` for upstream binaries as well hmmmm
