### ISSUE TITLE
Can't use `nvim` from non-administrative terminal on Windows

### ISSUE THREAD

**Issue by ok-nick** [MordechaiHadad/bob#65]
When installing and switching to a new version of neovim, the `nvim` command can only be accessed on an administrative terminal. I've tested installing and switching on both non-administrative and administrative terminals only to get the same issue. I was able to fix it by restarting my computer, although that shouldn't be necessary.

For some background, this is my first time installing and using `bob`. I was also using PowerShell.

**Comment by MordechaiHadad** [comment]
@ok-nick yeah this shouldn't happen at all.. the only time you would need to run terminal in admin mode is when running `use` cmd, could you run `bob erase` and try reinstalling a version and see if this happens again?
Also at what folder did bob symbolically linked neovim?

**Comment by ok-nick** [comment]
It seems to work fine now after trying the steps you suggested. Could've just been a problem with PowerShell?

Also, why does `bob` require administrative access at all?

**Comment by MordechaiHadad** [comment]
> Could've just been a problem with PowerShell?

I genuinely have no idea, as I got no idea how to reproduce this.

 > Also, why does bob require administrative access at all?
 
 Only required for linking, I can use `mklink` but that will require you to use cmd(truly great design idea by microsoft) and dealing with subprocesses errors is a bit more annoying than native rust errors.

**Comment by ok-nick** [comment]
What needs to be symlinked anyways?

**Comment by MordechaiHadad** [comment]
@ok-nick neovim binary/exe is symbolically linked to a specific path so you don't really have to manage the PATH variable everytime u switch to a new version.
Anyway can I close this issue(if ur issues is fixed)?

**Comment by ok-nick** [comment]
The issue is not fixed but it's also not reproducible. I'll close it for now since there's not much more information that could be obtained
