### ISSUE TITLE
Use proxy executable

### ISSUE THREAD

**Issue by ok-nick** [MordechaiHadad/bob#66]
According to #65, `bob` uses symlinks to `nvim` to avoid updating the `PATH` each time the version is switched. This comes with numerous issues, with one being Windows requiring administrative privileges.

To solve this, use a proxy executable named `nvim` that is in the `PATH`, that simply redirects to the currently used `nvim` executable. This process is used by `rustup`/`cargo`, as well as [aftman](https://github.com/LPGhatguy/aftman) (which you could reference). It allows much more flexibility for how `nvim` is called and used, and avoids the need for administrative privileges to create symlinks. It may come with other benefits as well, but I'd have to do more research.

**Comment by MordechaiHadad** [comment]
@ok-nick could you elaborate on that? I am unable to wrap my head around this idea tbh.

**Comment by ok-nick** [comment]
Yes, so from my understanding `aftman` copies itself into a bin folder (which is in the `PATH`) with its name corresponding to the tool name.
Example:
![image](https://user-images.githubusercontent.com/25470747/200139652-ed721f40-27ec-4c20-a805-f81a9a533cd0.png)
Each executable you see above is a different tool managed by `aftman`.

The executables themselves aren't actually the tool though, they are just a clone of the `aftman` executable itself. As you can see [here](https://github.com/LPGhatguy/aftman/blob/f69ee9f98f69f8d62257db763ffbd998b88ef56c/src/main.rs#L34-L64), `aftman` checks in `main.rs` if it was run under the `bin` folder. If so, it knows that it's a proxy executable and it's supposed to passthrough to the actual tool. Before it does that, it finds the selected version then goes through the sub-directories and calls the tool.

![image](https://user-images.githubusercontent.com/25470747/200140327-5b6661da-9514-4872-8f10-568408f526e4.png)
Here is an image of the tool storage. You can see how there is a sub-directory inside each tool for each version of it. Obviously, `bob` won't be the same since it's only managing one tool, but you get the idea.

**Comment by MordechaiHadad** [comment]
Hmm this is really cool ngl, but don't you need to have sudo/admin privs to copy the executable into a directory that is `PATH`(at least most of them)

**Comment by ok-nick** [comment]
`aftman` doesn't require administrative privileges and it works great.

**Comment by MordechaiHadad** [comment]
@ok-nick Fair enough ill check their codebase

**Comment by MordechaiHadad** [comment]
see where they clone it etc

**Comment by MordechaiHadad** [comment]
I haven't really had time to check aftman at all as I was working on another project, @ok-nick since from my understanding you use aftman what PATH does aftman clone itself to?(if you can tell me for windows, macos and linux it would be based)

**Comment by ok-nick** [comment]
Aftman is a toolchain manager, so it also manages itself. Everything is installed to a `.aftman/bin` folder.

**Comment by MordechaiHadad** [comment]
@ok-nick doesn't that mean you also need to add `.aftman/bin` to PATH manually?

**Comment by ok-nick** [comment]
`aftman` handles it automatically

**Comment by MordechaiHadad** [comment]
@ok-nick so it will required elevated privs to add the path to PATH env var

**Comment by MordechaiHadad** [comment]
I might start this soon, main setback for now is understanding how to kill neovim when bob itself is killed.
