### ISSUE TITLE
Possibly incorrect version match

### ISSUE THREAD

**Issue by lawrence-laz** [MordechaiHadad/bob#67]
Running:
```
bob use 0.8.0
```
Installs:
```
$ nvim -v
NVIM v0.8.0-1210-gd367ed9b2
```

Given that neovim has two matches:
 - [NVIM v0.8.0-1210-gd367ed9b2](https://github.com/neovim/neovim/releases/tag/stable)
 - [NVIM v0.8.0](https://github.com/neovim/neovim/releases/tag/v0.8.0)

I initially expected the latter one to be installed, but got the former one.

Is this to be expected, or is this a mistake?

**Comment by MordechaiHadad** [comment]
@lawrence-laz It's not the expected behavior, I have downloaded both versions from github releases but `nvim -v` always gave me `NVIM v0.8.0-1210-gd367ed9b2`.
It's an issue with github's API i have no control over that.
