### ISSUE TITLE
Feautre request - Export current version to a local file

### ISSUE THREAD

**Issue by Avishayy** [MordechaiHadad/bob#80]
Hey, thank you for developing `bob`!

I want to track the current nvim version I use, specifically track it using version control, so if a plugin / configuration I use stopped working after changing neovim's version, I would be able to tell so after a while if I haven't seen the issue immediately.

What's nice is that using `bob install` (without an argument) can now look at that configured file and install the version from there rather than expect the version. (WIth an appropriate log message)

Ideally, this would be a config, and I'd use a workflow of this sort:
```sh
bob use 0.9.0
# bob writes the 0.9.0 to a preconfigured file, let's say `/Users/user/.config/nvim/bob.version`
git add bob.version
git commit -m "neovim upgraded to 0.9.0"
```

Then it'd be really easy for me to see when I actually changed versions, and potentially I can also use `git bisect` to find out if the reason my config suddenly has issues is due to upgrading the version (of course, `bob install` would be needed between each step)

Right now I implemented this for myself using simple zsh wrappers around `bob install`, but having this as a built-in feature would be really nice.

If it's something you want to support, I'll gladly work on it and open a PR.

**Comment by MordechaiHadad** [comment]
there is a file called `used` in the installation directory, does that fit your request?

**Comment by Avishayy** [comment]
Unfortunately no, for two reasons:
1. Unconfigurable path, I want the file to exist in my dotfiles, specifically my neovim configuration. Yes, I can configure the downloads directory path, but it means that the versions will be downloaded to the same directory, which I don't like.
2. Lack of implicit `bob install`, I would want `bob install` (or perhaps it should be `bob use`) without arguments to use the version stored in that same file, and that's not the current behavior, nor it is configurable

**Comment by MordechaiHadad** [comment]
Hey! If you are up to the task you are free to open a PR to add a configurable path to the version file.
But don't add an implicit `bob install`, i personally don't like implicity.

**Comment by Avishayy** [comment]
Sure!

I'd still want to have a command that reads the version from the current version file, how about a new command, `bob sync`?

**Comment by MordechaiHadad** [comment]
Sounds good, make it work like a lock file or something
