### ISSUE TITLE
Typo in tag

### ISSUE THREAD

**Issue by orhun** [MordechaiHadad/bob#87]
Hello!

Regarding [b43e18efb0ccd4f55bdfc20c5bded4ae0e36ff50](https://github.com/MordechaiHadad/bob/commit/b43e18efb0ccd4f55bdfc20c5bded4ae0e36ff50), is it possible that you re-push the tag as `2.0.0` or release `2.0.1`?

\- the AUR maintainer 🐻

**Comment by MordechaiHadad** [comment]
I will re-push it, why exactly is that an issue btw?

**Comment by orhun** [comment]
Thanks! It's against [semver](https://semver.org/) as you might've already guessed.

**Comment by MordechaiHadad** [comment]
@orhun I updated the release, can you check again the tag?

**Comment by orhun** [comment]
Yup, that worked. Thanks!
