### ISSUE TITLE
Add Linux ARM build for M1 devices

### ISSUE THREAD

**Issue by 0atman** [MordechaiHadad/bob#91]
Hello from Asahi Linux! Could you add `aarch64-linux` for m1 linux please?

I'm hoping this can be as simple as it was for #22 ?

Thank you so much! :smiley:

**Comment by 0atman** [comment]
My details:

```sh
$ name -a
Linux oatman-m1 6.1.0-asahi-2-2-edge-ARCH #2 SMP PREEMPT_DYNAMIC Fri, 16 Dec 2022 05:04:23 +0000 aarch64 GNU/Linux
```

**Comment by 0atman** [comment]
Added #92 which with some noodling by someone clever could work!

**Comment by MordechaiHadad** [comment]
@0atman how do you even manage to run neovim on ARM? neovim doesn't provide ARM binaries.

**Comment by MordechaiHadad** [comment]
solved
